import React, { createContext, useContext, useState } from 'react';

const LanguageContext = createContext();

export const translations = {
  en: {
    announcement: "MNRE Approved & ISO 9001:2015 Certified | Tamil Nadu, India",
    subsidyBadge: "40% - 60% Govt Subsidy Eligible",
    navHome: "Home",
    navAbout: "About Us",
    navDryers: "Solar Dryers",
    navApplications: "Applications",
    navGallery: "Gallery",
    navStories: "Farmer Stories",
    navMap: "Interactive Map",
    navContact: "Contact Us",
    getQuote: "Get Free Quote",
    heroBadge: "Next-Gen Solar Thermal Food Preservation Technology",
    heroTitle1: "Stop Post-Harvest Loss.",
    heroTitle2: "Multiply Your Farm Profits.",
    heroSubtitle: "Hygienic, 100% solar-powered thermal dehydration that retains color, aroma, and natural nutrients without electricity bills.",
    calcSavings: "Calculate My Savings",
    exploreModels: "Explore Dryer Models",
    dryersInstalled: "Dryers Installed",
    foodSaved: "Food Saved / Year",
    subsidyHelp: "Govt Subsidy Assistance",
    mnreBadge: "MNRE Approved & Enlisted",
    isoBadge: "ISO 9001:2015 Certified Quality",
    subsidyBadge2: "100% Eligible for State Subsidies",
    roiTitle: "Interactive Profit & Sizing Calculator",
    roiSubtitle: "Select your crop and daily harvest quantity to estimate drying speedup & profits.",
    selectCrop: "1. Select Your Crop / Material",
    batchQty: "2. Batch Harvest Quantity (kg)",
    sunDrying: "Open Sun Drying",
    solarDrying: "ZeniTEK Solar Dryer",
    daysFaster: "Days Faster (100% Sealed)",
    priceIncrease: "Market Price Premium",
    profitPerBatch: "Est. Profit & Savings / Batch",
    recSetup: "Recommended Setup",
    getQuoteSetup: "Get Quote for This Setup",
    annualValueGain: "Est. Annual Value Addition (45 batches)",
    estRoi: "ESTIMATED RETURN ON INVESTMENT",
    modelsHeading: "Choose the Perfect Solar Thermal Dryer for Your Farm",
    modelsSubtitle: "From portable 10 kg batch units to heavy multi-tunnel plants for exporters.",
    reqQuote: "Request Price Quote",
    whatCanYouDry: "What Can You Dry With ZeniTEK?",
    viewAllCrops: "View All 50+ Crops Matrix",
    whyChooseUs: "Why Choose ZeniTEK Solar?",
    climateResilient: "Climate Resilient",
    climateDesc: "Works seamlessly on cloudy days with smart heat retention.",
    zeroOpCost: "Zero Operating Cost",
    zeroOpDesc: "100% sun-powered. Zero wood, zero coal, zero power bills.",
    hygienicSetup: "100% Hygienic Setup",
    hygienicDesc: "Fully sealed enclosure prevents dust, insects, and rain spoilage.",
    marketLinkage: "Market Linkage Support",
    marketDesc: "Direct B2B corporate buyer connection for dried produce.",
    trustedBy: "Trusted by 1,200+ Agricultural Entrepreneurs",
    quickFormTitle: "Get Instant Pricing & Subsidy Details on WhatsApp",
    quickFormDesc: "Fill this 30-second form to receive custom dryer pricing, sizing, and subsidy guidelines.",
    yourName: "Your Name",
    whatsappNum: "WhatsApp Number",
    districtCity: "State / District",
    targetCrop: "Target Crop",
    getSubsidyQuote: "Get Pricing & Subsidy Quote",
    factoryLocation: "Offices & Operations",
    callUs: "Call Engineering Support",
    emailUs: "Email Sales Team",
    chatWhatsapp: "Chat Instantly on WhatsApp",
    userCategory: "User Category",
    desiredCapacity: "Desired Daily Capacity",
    additionalReqs: "Additional Requirements",
    submitProposal: "Submit & Request Formal Proposal",
    seeMoreDetails: "See More Details",
    enquireSetup: "Enquire Setup",
    projectDetails: "Installation Case Details",
    moistureReduction: "Moisture Parameter Target",
    close: "Close",
    matrixModelBadge: "TECHNICAL SPECIFICATION COMPARISON",
    matrixModelTitle: "Model Technical Comparison Matrix",
    matrixModelSubtitle: "Side-by-side specifications, capacity ratings, heat retention performance, and government subsidy guidelines.",
    matrixCropBadge: "CROP DEHYDRATION PROFILES",
    matrixCropTitle: "Crop Moisture Parameter Matrix",
    matrixCropSubtitle: "Target moisture retention and drying duration comparison: ZeniTEK Solar Thermal vs Open Sun Drying.",
    searchPlaceholder: "Search crop or profit benefit...",
    dryerModel: "Dryer Model",
    descriptionReqs: "Description / Requirements",
    getPricingSubsidyQuote: "GET PRICING & SUBSIDY QUOTE",
    
    // About Us Page
    aboutBadge: "ABOUT ZENITEK SOLAR THERMAL",
    aboutTitle1: "Empowering Farmers.",
    aboutTitle2: "Eliminating Post-Harvest Waste.",
    aboutSubtitle: "With Registered Office in Erode and Incubation & Operation Center at SSM College of Engineering, Komarapalayam, Namakkal, ZeniTEK designs and manufactures state-of-the-art polyhouse greenhouse solar thermal dryers for global agriculture.",
    aboutHub: "MANUFACTURING & INNOVATION HUB",
    aboutInnovation: "Over 2 Decades of Solar Thermal Innovation",
    aboutP1: "ZeniTEK was founded with a single mission: to stop agricultural decay by putting clean, sun-powered thermal technology directly into the hands of farmers and smallholder cooperatives.",
    aboutP2: "Our dedicated manufacturing facility and Incubation Center at SSM College of Engineering integrate advanced thermal dynamics research with precision structural steel fabrication to deliver 100% weather-proof dryers.",
    aboutF1: "✓ 25,000+ Sq. Ft. Factory",
    aboutF2: "✓ In-House Thermal Testing Lab",
    aboutPillarsTitle: "Our 3 Technology Pillars",
    aboutPillarsSubtitle: "Engineering excellence built into every solar dryer we construct.",
    pillar1Title: "Research & Innovation",
    pillar1Desc: "Center for Excellence focusing on fluid dynamics, thermal storage mass, and UV polycarbonate light amplification.",
    pillar2Title: "Quality & Standards",
    pillar2Desc: "Precision manufacturing conforming to strict ISO 9001:2015 standards and CE safety certifications.",
    pillar3Title: "Carbon Footprint Offset",
    pillar3Desc: "Replacing fossil-fuel food drying to offset over 15,000 MT of CO₂ emissions annually across rural India.",
    impact1: "Farmers & FPOs Served",
    impact2: "Food Waste Prevented",
    impact3: "Farmer Income Rise",
    impact4: "Subsidy Assistance",
    govtBadgesTitle: "Govt Approvals & Quality Badges",
    mnreApproved: "MNRE Approved Manufacturer",
    isoSystem: "ISO 9001:2015 Quality System",
    ceMarked: "CE Marked Thermal Components",
    consultEngineers: "Consult Our Thermal Engineers",

    // Applications Page
    appMatrixBadge: "MULTI-CROP APPLICATION MATRIX",
    appMatrixTitle1: "Engineered to Dry Over",
    appMatrixTitle2: "50+ Agricultural & Industrial Products",
    appMatrixSubtitle: "Custom solar thermal dehydration profiles for maximum nutrient, color, and essential oil retention.",
    tabAgri: "🌾 Food & Agriculture (Copra, Moringa, Spices)",
    tabMarine: "🐟 Marine & Seafood (Salted Fish, Shrimp)",
    tabIndustrial: "🏭 Industrial & Biomass (Sludge, Rubber, Timber)",
    thTargetProduce: "Target Produce",
    thFreshMoisture: "Fresh Moisture %",
    thDriedMoisture: "Dried Moisture %",
    thSolarTime: "ZeniTEK Solar Time",
    thSunTime: "Open Sun Time",
    thProfitBenefit: "Key Profit Benefit",
    tailoredSolutions: "Tailored Solutions for Your Operations",
    personaFpoTitle: "For FPOs & Cooperatives",
    personaFpoDesc: "Community polyhouse dryers handling 500 kg+ daily harvests for member farmers.",
    personaFpoBtn: "Request FPO Proposal →",
    personaExpTitle: "For Food Exporters",
    personaExpDesc: "Automated moisture-controlled dryers certified for EU, US-FDA, and Middle-East export compliance.",
    personaExpBtn: "Request Exporter Quote →",
    personaFarmerTitle: "For Smallholder Farmers",
    personaFarmerDesc: "Affordable entry-level DIY portable dryers with 40% government subsidy eligibility.",
    personaFarmerBtn: "Request Farmer Quote →",

    // Contact Us Page
    contactBadge: "DIRECT FACTORY CONTACT",
    contactTitle1: "Let’s Build Your Sustainable",
    contactTitle2: "Drying Solution.",
    contactSubtitle: "Contact our engineering and sales team for custom moisture analysis, subsidy assistance, and factory-direct pricing.",
    regOfficeLabel: "Reg. Office (Main Address)",
    regOfficeAddress: "4/501, Aitreya garden, Athappam palayam, Vallipurathanpalayam (PO), Erode (Dt), Tamil Nadu, PIN: 638 112",
    opOfficeLabel: "Operation Address",
    opOfficeAddress: "Zenitek Incubation center, SSM College of Engineering, NH-544, Valayakaranur, Komarapalayam, Namakkal Dt. - 638 183",
    gstinLabel: "GSTIN",
    gstinNumber: "33AACFZ8530G1Z5",
    primaryPhone: "+91-8903852623",
    primaryEmail: "zenitek2k@gmail.com",
    factoryAddressLabel: "Reg. Office (Main Address)",
    factoryAddressText: "4/501, Aitreya garden, Athappam palayam, Vallipurathanpalayam (PO), Erode (Dt), Tamil Nadu, PIN: 638 112",
    operationAddressLabel: "Operation Address",
    operationAddressText: "Zenitek Incubation center, SSM College of Engineering, NH-544, Valayakaranur, Komarapalayam, Namakkal Dt. - 638 183",
    workingHours: "Mon - Sat: 9:00 AM - 7:00 PM IST",
    preQualTitle: "Pre-Qualifying Quote & Sizing Enquiry",
    support1: "Free Government Subsidy Eligibility Check",
    support2: "Custom Moisture-Analysis Sizing Consults",
    support3: "100% On-Farm Setup & Operator Training",
    csrBadge: "CSR & NGO PARTNERSHIP PORTAL",
    csrTitle: "Partner with ZeniTEK for Rural Livelihood Projects",
    csrDesc: "We collaborate with CSR foundations, NABARD, and agricultural NGOs to deploy solar dryers for rural women self-help groups.",
    csrBtn: "Request CSR Partnership Pitch",

    // Farmer Stories Page
    storiesBadge: "FARMER PROSPERITY STORIES",
    storiesTitle1: "Real Stories. Real Prosperity.",
    storiesTitle2: "Zero Food Waste.",
    storiesSubtitle: "Hear directly from farmers, self-help groups, and FPO presidents who multiplied their post-harvest margins with ZeniTEK.",
    impactFamilies: "Rural Families Empowered",
    impactValue: "Total Farmer Value Added",
    impactCrops: "Crops Saved from Mold",
    impactCleanEnergy: "Sun Powered Clean Energy",
    videoReviewsTitle: "Regional Client Video Reviews",
    videoReviewsSub: "Watch full on-farm interviews with clients in Tamil Nadu, Kerala & Maharashtra.",
    caseStudiesTitle: "In-Depth Case Studies",
    pollachiCollective: "Pollachi Coconut Farmers Collective",
    pollachiTitle: "How 50 Coconut Farmers Eliminated Rain Losses & Increased Copra Revenue by 28%",
    probTitle: "The Problem",
    probDesc: "Unseasonal monsoon rains destroyed 30% of copra with mold stains.",
    solTitle: "Solar Solution",
    solDesc: "500 kg Polyhouse Solar Dryer installed with 50% State Agri Subsidy.",
    resTitle: "Profit Result",
    resDesc: "100% Grade-1 White Copra dried in 2.5 days. Extra profit of ₹18/kg.",
    commitmentTitle: "Our 360° Partner Support Commitment",
    comm1Title: "End-to-End Subsidy Clearance",
    comm1Desc: "We file all government agritech subsidy applications and bank loan tie-ups on your behalf.",
    comm2Title: "On-Farm Installation & Training",
    comm2Desc: "Our Coimbatore engineers install the setup on your farm and train your team on crop parameters.",
    comm3Title: "Direct B2B Buyer Linkage",
    comm3Desc: "We connect FPOs with certified corporate food exporters buying premium dried produce.",
    startProsperityBtn: "Start Your Prosperity Story Today",

    // Gallery Page
    galleryBadge: "PROJECT & PRODUCE GALLERY",
    galleryTitle1: "Visual Tour of ZeniTEK Solar",
    galleryTitle2: "Thermal Dryers & Dried Produce",
    gallerySubtitle: "Explore real-world field installations across Tamil Nadu, Kerala, Andhra Pradesh, and Karnataka. See the 100% white copra, vibrant moringa powder, and hygienic dry fish produce.",
    catAll: "All Photos",
    catInstallations: "Field Installations",
    catProduce: "Dried Produce Quality",
    catModels: "Dryer Models",
    catFactory: "Factory & Assembly",
    viewEnlarged: "View Enlarged Image",
    clickFullSpec: "Click for Full Specification",
    customDryerBadge: "GET YOUR OWN CUSTOM SOLAR DRYER",
    customDryerTitle: "Want a Similar High-Yield Polyhouse Solar Dryer Setup?",
    customDryerDesc: "We design, manufacture, and assemble solar dryers with end-to-end 40%-60% government subsidy filing support.",
    locationLabel: "Location:",
    requestQuoteForModel: "Request Quote for this Model",

    // Solar Dryers Page
    catalogueBadge: "SOLAR DRYER CATALOGUE",
    catalogueTitle1: "100% Solar-Powered Dehydration.",
    catalogueTitle2: "5x Faster. Zero Operating Costs.",
    catalogueSubtitle: "Explore our range of UV-stabilized polycarbonate polyhouse solar thermal dryers engineered for maximum thermal heat retention. Click any model to view full technical specifications.",
    browseCapacity: "Browse by Daily Capacity",
    browseCrop: "Browse by Crop Type",
    clickSpecs: "Click for Full Specifications",
    targetAudienceLabel: "Target Audience",
    buildMaterialLabel: "Build Material",
    tempRangeLabel: "Temp Range",
    subsidyEligibilityLabel: "Subsidy Eligibility",
    viewSpecsPhotos: "View Specifications & Photos",
    checkSubsidyPricing: "Check Subsidy & Pricing",
    thSpecParam: "Specification Parameter",
    thPortable: "Portable DIY Dryer",
    thPolyhouse: "Commercial Polyhouse",
    thIndustrial: "Multi-Tunnel Industrial",
    stateAssistance: "STATE GOVERNMENT ASSISTANCE",
    claimSubsidyTitle: "Claim Up to 60% Government Subsidy on Your Solar Dryer",
    claimSubsidyDesc: "We handle end-to-end documentation, NABARD application filing, and state agritech subsidy clearance.",
    checkSubsidyBtn: "Check Subsidy Eligibility",

    // Map Page & Component
    mapShowcaseBadge: "GEOGRAPHICAL WORK SHOWCASE",
    mapTitle1: "Active Solar Dryer Installations",
    mapTitle2: "Across South India & Beyond",
    mapSubtitle: "Explore our interactive project map. Click any marker or filter by state on the sidebar to view active polyhouse dryer installations, capacities, and crop moisture results.",
    filterStateLabel: "Filter State:",
    interactiveMapTab: "Interactive Map",
    projectListTab: "Project List",
    visitTitle: "Want to Visit an Active Solar Dryer Installation Near You?",
    visitDesc: "We arrange live site visits for FPO directors, government officials, and farmers.",
    bookVisitBtn: "Book Live Site Visit",

    // Footer
    footerAbout: "ZeniTEK is India's leading designer & manufacturer of high-efficiency polyhouse greenhouse solar thermal dryers. Engineered in Coimbatore to eliminate post-harvest waste for farmers, FPOs, and exporters.",
    footerDryerModels: "Dryer Models",
    footerDownloads: "Downloads & Guides",
    footerCatalog: "Product Catalog (PDF)",
    footerSubsidyGuide: "Govt Subsidy Guide 2026",
    footerLabReport: "Copra Lab Test Report",
    footerCoimbatoreFactory: "Offices & Operations",
    footerOffices: "Offices & Operations",
    footerRights: "All rights reserved.",
    footerPrivacy: "Privacy Policy",
    footerTerms: "Terms of Service",

    // Crops
    cropCopra: "Copra / Coconut",
    cropMoringa: "Moringa / Herbs / Tea",
    cropSpices: "Red Chillies / Spices",
    cropFruits: "Fruits & Vegetables",
    cropFish: "Salted Fish & Seafood",
    cropOther: "Other Biomass & Crops",

    // Models
    modelPortable: "Portable DIY Solar Dryer",
    modelPolyhouse: "Commercial Polyhouse Tunnel Dryer",
    modelIndustrial: "Multi-Tunnel Industrial Hybrid Dryer"
  },

  ta: {
    announcement: "MNRE அங்கீகாரம் & ISO 9001:2015 சான்றளிக்கப்பட்டது | தமிழ்நாடு, இந்தியா",
    subsidyBadge: "40% - 60% அரசு மானியம் பெறத் தகுதியானது",
    navHome: "முகப்பு",
    navAbout: "எங்களைப் பற்றி",
    navDryers: "சோலார் உலர்த்திகள்",
    navApplications: "பயன்பாடுகள்",
    navGallery: "படத்தொகுப்பு",
    navStories: "விவசாயி கதைகள்",
    navMap: "ஊடாடும் வரைபடம்",
    navContact: "தொடர்பு கொள்ள",
    getQuote: "இலவச விலைப்புள்ளி பெற",
    heroBadge: "அடுத்த தலைமுறை சோலார் உணவு பதப்படுத்தும் தொழில்நுட்பம்",
    heroTitle1: "அறுவடைக்குப் பிந்தைய இழப்பைத் தடுப்போம்.",
    heroTitle2: "விவசாய லாபத்தை பன்மடங்கு பெருக்குவோம்.",
    heroSubtitle: "மின்சாரக் கட்டணம் இன்றி நிறம், மணம் மற்றும் இயற்கை ஊட்டச்சத்துக்களைக் காக்கும் 100% சூரிய ஒளி உலர்த்தி.",
    calcSavings: "எனது சேமிப்பைக் கணக்கிடுக",
    exploreModels: "உலர்த்தி மாடல்களைக் காண்க",
    dryersInstalled: "நிறுவப்பட்ட உலர்த்திகள்",
    foodSaved: "ஆண்டுக்கு சேமிக்கப்பட்ட உணவு",
    subsidyHelp: "அரசு மானிய உதவி",
    mnreBadge: "MNRE அங்கீகரிக்கப்பட்ட தயாரிப்பு",
    isoBadge: "ISO 9001:2015 தரச் சான்றிதழ்",
    subsidyBadge2: "100% மாநில மானியத் தகுதி",
    roiTitle: "லாப மற்றும் அளவு கணக்கீடு",
    roiSubtitle: "உங்கள் பயிர் மற்றும் தினசரி விளைச்சலைத் தேர்ந்தெடுத்து உலர்த்தும் வேகத்தையும் லாபத்தையும் கணக்கிடுங்கள்.",
    selectCrop: "1. பயிர் / பொருளைத் தேர்ந்தெடுக்கவும்",
    batchQty: "2. தொகுதி விளைச்சல் அளவு (கி.கி)",
    sunDrying: "திறந்தவெளி சூரிய உலர்த்தல்",
    solarDrying: "ஜெனிலெக் சோலார் உலர்த்தி",
    daysFaster: "நாட்கள் அதிவேக உலர்த்தல் (பாதுகாப்பானது)",
    priceIncrease: "சந்தை விலை உயர்வு %",
    profitPerBatch: "ஒரு தொகுதிக்கு எதிர்பார்க்கப்படும் லாபம்",
    recSetup: "பரிந்துரைக்கப்படும் உலர்த்தி",
    getQuoteSetup: "இதற்கான விலைப்புள்ளி பெற",
    annualValueGain: "ஆண்டு கூடுதல் லாபம் (45 தொகுதிகள்)",
    estRoi: "எதிர்பார்க்கப்படும் முதலீட்டு லாபம்",
    modelsHeading: "உங்கள் பண்ணைக்கு ஏற்ற சோலார் உலர்த்தியைத் தேர்ந்தெடுக்கவும்",
    modelsSubtitle: "10 கி.கி சிறிய உலர்த்தி முதல் 1 டன் தொழில்முறை உலர்த்தி வரை.",
    reqQuote: "விலைப்புள்ளி கேட்க",
    whatCanYouDry: "ஜெனிலெக் மூலம் எவற்றையெல்லாம் உலர்த்தலாம்?",
    viewAllCrops: "அனைத்து 50+ பயிர் அட்டவணையைக் காண்க",
    whyChooseUs: "ஏன் ஜெனிலெக் சோலார்?",
    climateResilient: "காலநிலை தாங்கும் திறன்",
    climateDesc: "மேகமூட்டமான நாட்களிலும் வெப்பத்தைத் தக்கவைத்துச் செயல்படும்.",
    zeroOpCost: "பூஜ்ஜிய இயக்கச் செலவு",
    zeroOpDesc: "100% சூரிய ஒளி சக்தி. விறகு இல்லை, கரண்ட் பில் இல்லை.",
    hygienicSetup: "100% சுகாதாரமான உலர்த்தல்",
    hygienicDesc: "தூசி, பூச்சிகள் மற்றும் மழைப் பாதிப்பிலிருந்து முழுப் பாதுகாப்பு.",
    marketLinkage: "சந்தை இணைப்பு உதவி",
    marketDesc: "உலர்ந்த பொருட்களுக்கு நேரடி கார்ப்பரேட் வாங்குபவர் இணைப்பு.",
    trustedBy: "1,200+ விவசாயிகளால் நம்பப்படுகிறது",
    quickFormTitle: "வாட்ஸ்அப்பில் உடனடி விலை விவரம் & மானியம் பெற",
    quickFormDesc: "விலை மற்றும் மானிய வழிகாட்டுதல்களைப் பெற 30 வினாடி படிவத்தைப் பூர்த்தி செய்யவும்.",
    yourName: "உங்கள் பெயர்",
    whatsappNum: "வாட்ஸ்அப் எண்",
    districtCity: "மாநிலம் / மாவட்டம்",
    targetCrop: "உலர்த்தும் பயிர்",
    getSubsidyQuote: "விலை விவரம் & மானியம் பெற",
    factoryLocation: "தலைமை அலுவலகம் & செயல்பாட்டு மையம்",
    callUs: "பொறியியல் உதவிக்கு அழைக்கவும்",
    emailUs: "விற்பனை பிரிவுக்கு மின்னஞ்சல் செய்ய",
    chatWhatsapp: "வாட்ஸ்அப்பில் உடனடியாக அரட்டையடிக்க",
    userCategory: "பயனர் பிரிவு",
    desiredCapacity: "தேவையான உலர்த்தி திறன்",
    additionalReqs: "கூடுதல் விவரங்கள்",
    submitProposal: "சமர்ப்பித்து அதிகாரப்பூர்வ மதிப்பீடு பெற",
    seeMoreDetails: "கூடுதல் விவரங்கள் காண்க",
    enquireSetup: "விலைப்புள்ளி கேட்க",
    projectDetails: "திட்டத்தின் முழு விவரங்கள்",
    moistureReduction: "ஈரப்பத அளவு இலக்கு",
    close: "மூடுக",
    matrixModelBadge: "தொழில்நுட்ப விவரக்குறிப்பு ஒப்பீடு",
    matrixModelTitle: "மாடல் தொழில்நுட்ப ஒப்பீட்டு அட்டவணை",
    matrixModelSubtitle: "அனைத்து ஜெனிலெக் உலர்த்தி மாடல்களின் திறன்கள், வெப்பநிலை மற்றும் அரசு மானிய வழிகாட்டுதல்கள்.",
    matrixCropBadge: "பயிர் உலர்த்தும் அளவுருக்கள்",
    matrixCropTitle: "பயிர் ஈரப்பதம் ஒப்பீட்டு அட்டவணை",
    matrixCropSubtitle: "ஈரப்பதம் மற்றும் உலர்த்தும் நேர ஒப்பீடு: ஜெனிலெக் சோலார் உலர்த்தி மற்றும் திறந்தவெளி சூரிய உலர்த்தல்.",
    searchPlaceholder: "பயிர் அல்லது நன்மைகளைத் தேடுக...",
    dryerModel: "உலர்த்தி மாடல்",
    descriptionReqs: "விளக்கம் / கூடுதல் தேவைகள்",
    getPricingSubsidyQuote: "விலை விவரம் & மானியம் பெற",

    // About Us Page
    aboutBadge: "ஜெனிலெக் சோலார் பற்றி",
    aboutTitle1: "விவசாயிகளுக்கு அதிகாரமளித்தல்.",
    aboutTitle2: "அறுவடைக்குப் பிந்தைய இழப்பைத் தடுத்தல்.",
    aboutSubtitle: "கோயம்பத்தூரில் அமைந்துள்ள ஜெனிலெக், விவசாயிகளுக்காக உலகத் தரம் வாய்ந்த பாலிஹவுஸ் சோலார் உலர்த்திகளை வடிவமைத்து தயாரிக்கிறது.",
    aboutHub: "கோயம்பத்தூர் உற்பத்தி மையம்",
    aboutInnovation: "20 ஆண்டுகளுக்கும் மேலான சோலார் வெப்ப கண்டுபிடிப்பு",
    aboutP1: "விவசாயக் கழிவுகளைத் தடுத்து, சூரிய ஆற்றல் உலர்த்தும் தொழில்நுட்பத்தை விவசாயிகளின் கைகளில் சேர்ப்பதே எங்கள் நோக்கம்.",
    aboutP2: "எங்களது 25,000 சதுர அடி தொழிற்சாலையில் உயர் தரக் கட்டுப்பாடுகளுடன் சோலார் உலர்த்திகள் தயாரிக்கப்படுகின்றன.",
    aboutF1: "✓ 25,000+ சதுர அடி தொழிற்சாலை",
    aboutF2: "✓ சொந்த வெப்ப சோதனை ஆய்வகம்",
    aboutPillarsTitle: "எங்கள் 3 தொழில்நுட்பத் தூண்கள்",
    aboutPillarsSubtitle: "நாங்கள் உருவாக்கும் ஒவ்வொரு உலர்த்தியிலும் பொறிக்கப்பட்டுள்ள பொறியியல் சிறப்புகள்.",
    pillar1Title: "ஆராய்ச்சி & கண்டுபிடிப்பு",
    pillar1Desc: "வெப்ப சேமிப்பு மற்றும் UV பாலிஹவுஸ் ஒளிக் கட்டுப்பாட்டு மையத்தின் மேம்பட்ட தொழில்நுட்பம்.",
    pillar2Title: "தரம் & தரநிலைகள்",
    pillar2Desc: "ISO 9001:2015 மற்றும் CE பாதுகாப்புச் சான்றிதழ்களின்படி துல்லியமான தயாரிப்பு.",
    pillar3Title: "கார்பன் உமிழ்வு குறைப்பு",
    pillar3Desc: "பாரம்பரிய உலர்த்தல் முறைகளை மாற்றி ஆண்டுக்கு 15,000 டன் CO₂ உமிழ்வைக் குறைத்தல்.",
    impact1: "பயனடைந்த விவசாயிகள் & FPOக்கள்",
    impact2: "தடுக்கப்பட்ட உணவு வீணடிப்பு",
    impact3: "விவசாயி வருமான உயர்வு",
    impact4: "அரசு மானிய உதவி பெறப்பட்டது",
    govtBadgesTitle: "அரசு அங்கீகாரங்கள் & தரச் சான்றிதழ்கள்",
    mnreApproved: "MNRE அங்கீகரிக்கப்பட்ட உற்பத்தியாளர்",
    isoSystem: "ISO 9001:2015 தர அமைப்பு",
    ceMarked: "CE சான்றளிக்கப்பட்ட பாகங்கள்",
    consultEngineers: "எங்கள் பொறியாளர்களைத் தொடர்பு கொள்ள",

    // Applications Page
    appMatrixBadge: "பல்வேறு பயிர் பயன்பாட்டு அட்டவணை",
    appMatrixTitle1: "50+ க்கும் மேற்பட்ட பயிர்களை உலர்த்த",
    appMatrixTitle2: "வடிவமைக்கப்பட்ட சோலார் உலர்த்தி",
    appMatrixSubtitle: "ஊட்டச்சத்துக்கள், நிறம் மற்றும் மணத்தைப் பாதுகாக்கும் சோலார் உலர்த்தும் வழிகாட்டிகள்.",
    tabAgri: "🌾 உணவு & விவசாயம் (கொப்பரை, முருங்கை, மசாலா)",
    tabMarine: "🐟 கடல் உணவு (கருவாடு, இறால்)",
    tabIndustrial: "🏭 தொழில் துறை (ரப்பர், மரம், கழிவுகள்)",
    thTargetProduce: "பயிர் / பொருள்",
    thFreshMoisture: "ஆரம்ப ஈரப்பதம் %",
    thDriedMoisture: "இறுதி ஈரப்பதம் %",
    thSolarTime: "ஜெனிலெக் சோலார் நேரம்",
    thSunTime: "திறந்தவெளி நேரம்",
    thProfitBenefit: "முக்கிய லாப நன்மை",
    tailoredSolutions: "உங்கள் தேவைகளுக்கான சிறப்புத் தீர்வுகள்",
    personaFpoTitle: "விவசாய சங்கங்கள் (FPO) & கூட்டமைப்புகளுக்கு",
    personaFpoDesc: "தினசரி 500 கி.கி+ விளைச்சலை உலர்த்தும் சமுதாய பாலிஹவுஸ் உலர்த்திகள்.",
    personaFpoBtn: "FPO மதிப்பீடு கேட்க →",
    personaExpTitle: "உணவு ஏற்றுமதியாளர்களுக்கு",
    personaExpDesc: "சர்வதேச ஏற்றுமதித் தர நிலைகளுக்கு ஏற்ற தானியங்கி ஈரப்பதக் கட்டுப்பாட்டு உலர்த்திகள்.",
    personaExpBtn: "ஏற்றுமதி மதிப்பீடு கேட்க →",
    personaFarmerTitle: "சிறு விவசாயிகளுக்கு",
    personaFarmerDesc: "40% அரசு மானியத் தகுதியுடன் கூடிய கையடக்க உலர்த்திகள்.",
    personaFarmerBtn: "விவசாயி மதிப்பீடு கேட்க →",

    // Contact Us Page
    contactBadge: "நேரடி தொழிற்சாலை தொடர்பு",
    contactTitle1: "உங்கள் பண்ணைக்கு ஏற்ற உலர்த்தியை",
    contactTitle2: "உருவாக்குவோம்.",
    contactSubtitle: "மானிய உதவி மற்றும் நேரடி விலை விவரங்களுக்கு எங்கள் பொறியாளர்களைத் தொடர்பு கொள்ளுங்கள்.",
    regOfficeLabel: "பதிவு செய்யப்பட்ட தலைமை அலுவலகம்",
    regOfficeAddress: "4/501, ஆத்ரேயா கார்டன், அத்தப்பம்பாளையம், வள்ளிபுரத்தான்பாளையம் (அஞ்சல்), ஈரோடு (மாவட்டம்), தமிழ்நாடு, PIN: 638 112",
    opOfficeLabel: "செயல்பாட்டு முகவரி",
    opOfficeAddress: "ஜெனிலெக் இன்குபேஷன் சென்டர், எஸ்.எஸ்.எம் பொறியியல் கல்லூரி, NH-544, வளையக்காரனூர், குமாரபாளையம், நாமக்கல் (மாவட்டம்) - 638 183",
    gstinLabel: "GSTIN",
    gstinNumber: "33AACFZ8530G1Z5",
    primaryPhone: "+91-8903852623",
    primaryEmail: "zenitek2k@gmail.com",
    factoryAddressLabel: "பதிவு செய்யப்பட்ட தலைமை அலுவலகம்",
    factoryAddressText: "4/501, ஆத்ரேயா கார்டன், அத்தப்பம்பாளையம், வள்ளிபுரத்தான்பாளையம் (அஞ்சல்), ஈரோடு (மாவட்டம்), தமிழ்நாடு, PIN: 638 112",
    operationAddressLabel: "செயல்பாட்டு முகவரி",
    operationAddressText: "ஜெனிலெக் இன்குபேஷன் சென்டர், எஸ்.எஸ்.எம் பொறியியல் கல்லூரி, NH-544, வளையக்காரனூர், குமாரபாளையம், நாமக்கல் (மாவட்டம்) - 638 183",
    workingHours: "திங்கள் - சனி: காலை 9:00 - மாலை 7:00",
    preQualTitle: "முன்-தகுதி விலைப்புள்ளி & அளவு கோரிக்கை",
    support1: "இலவச அரசு மானியத் தகுதி சரிபார்ப்பு",
    support2: "தனிப்பயனாக்கப்பட்ட ஈரப்பத பகுப்பாய்வு",
    support3: "100% பண்ணை நிறுவல் & பயிற்சி",
    csrBadge: "CSR & NGO கூட்டாண்மை தளம்",
    csrTitle: "கிராமப்புற வாழ்வாதாரத் திட்டங்களுக்கு எங்களுடன் இணையுங்கள்",
    csrDesc: "மகளிர் சுயஉதவிக் குழுக்களுக்கு சோலார் உலர்த்திகளை வழங்க CSR நிறுவனங்களுடன் இணைந்து செயல்படுகிறோம்.",
    csrBtn: "CSR கூட்டாண்மை முன்மொழிவு கேட்க",

    // Farmer Stories Page
    storiesBadge: "விவசாயிகளின் வெற்றி கதைகள்",
    storiesTitle1: "உண்மையான கதைகள். உண்மை வளர்ச்சி.",
    storiesTitle2: "பூஜ்ஜிய உணவு விரயம்.",
    storiesSubtitle: "ஜெனிலெக் சோலார் மூலம் லாபத்தைப் பெருக்கிய விவசாயிகளின் நேரடி அனுபவங்கள்.",
    impactFamilies: "பயனடைந்த கிராமப்புற குடும்பங்கள்",
    impactValue: "விவசாயிகளுக்குக் கிடைத்த கூடுதல் மதிப்பு",
    impactCrops: "சேமிக்கப்பட்ட பயிர்கள்",
    impactCleanEnergy: "100% சூரிய ஒளி பசுமை ஆற்றல்",
    videoReviewsTitle: "வாடிக்கையாளர் வீடியோ கருத்துகள்",
    videoReviewsSub: "தமிழ்நாடு, கேரளா மற்றும் மகாராஷ்டிர விவசாயிகளின் நேரடி வீடியோ பேட்டிகள்.",
    caseStudiesTitle: "விரிவான ஆய்வு அறிக்கைகள்",
    pollachiCollective: "பொள்ளாச்சி தென்னை விவசாயிகள் கூட்டமைப்பு",
    pollachiTitle: "50 விவசாயிகள் மழைப் பாதிப்பைத் தடுத்து கொப்பரை வருவாயை 28% உயர்த்தியது எப்படி?",
    probTitle: "பிரச்சனை",
    probDesc: "பருவம் தப்பிய மழையால் 30% கொப்பரை பூசணம் பிடித்து வீணானது.",
    solTitle: "சோலார் தீர்வு",
    solDesc: "50% மாநில மானியத்துடன் 500 கி.கி பாலிஹவுஸ் சோலார் உலர்த்தி நிறுவப்பட்டது.",
    resTitle: "லாப முடிவு",
    resDesc: "100% முதல்தர வெள்ளை கொப்பரை 2.5 நாட்களில் உலர்ந்தது. கி.கி-க்கு ₹18 கூடுதல் லாபம்.",
    commitmentTitle: "எங்களின் 360° ஆதரவு உறுதிமொழி",
    comm1Title: "முழுமையான மானிய அனுமதி",
    comm1Desc: "அனைத்து அரசு மானிய விண்ணப்பங்கள் மற்றும் வங்கி கடன்களை நாங்கள் ஒருங்கிணைக்கிறோம்.",
    comm2Title: "பண்ணை நிறுவல் & பயிற்சி",
    comm2Desc: "எங்கள் கோயம்பத்தூர் பொறியாளர்கள் உங்கள் பண்ணையில் நிறுவி பயிற்சி அளிப்பார்கள்.",
    comm3Title: "நேரடி B2B வாங்குபவர் இணைப்பு",
    comm3Desc: "உலர்ந்த பொருட்களுக்கு நேரடி கார்ப்பரேட் ஏற்றுமதியாளர் இணைப்பை ஏற்படுத்துகிறோம்.",
    startProsperityBtn: "உங்கள் வெற்றிப் பயணத்தை இன்றே தொடங்குங்கள்",

    // Gallery Page
    galleryBadge: "திட்டங்கள் & படத்தொகுப்பு",
    galleryTitle1: "ஜெனிலெக் சோலார் உலர்த்திகள்",
    galleryTitle2: "மற்றும் உலர்ந்த பொருட்களின் படங்கள்",
    gallerySubtitle: "தமிழ்நாடு, கேரளா, ஆந்திரா மற்றும் கர்நாடகாவில் நிறுவப்பட்ட சோலார் உலர்த்திகள் மற்றும் தரமான விளைபொருட்கள்.",
    catAll: "அனைத்துப் படங்கள்",
    catInstallations: "நிறுவப்பட்ட இடங்கள்",
    catProduce: "உலர்ந்த பொருட்கள் தரம்",
    catModels: "உலர்த்தி மாடல்கள்",
    catFactory: "தொழிற்சாலை & உற்பத்தி",
    viewEnlarged: "பெரிதாக்கிப் பார்க்க",
    clickFullSpec: "முழு விவரக்குறிப்பு அறிய கிளிக் செய்க",
    customDryerBadge: "உங்கள் பண்ணைக்குச் சொந்தமான உலர்த்தி பெற",
    customDryerTitle: "இதே போன்ற சோலார் உலர்த்தி அமைக்க வேண்டுமா?",
    customDryerDesc: "40%-60% அரசு மானிய வழிகாட்டுதலுடன் சோலார் உலர்த்திகளை அமைத்து தருகிறோம்.",
    locationLabel: "இடம்:",
    requestQuoteForModel: "இந்த மாடலுக்கு விலைப்புள்ளி கேட்க",

    // Solar Dryers Page
    catalogueBadge: "சோலார் உலர்த்தி அட்டவணை",
    catalogueTitle1: "100% சூரிய ஒளி உலர்த்தல்.",
    catalogueTitle2: "5 மடங்கு வேகம். பூஜ்ஜிய மின்கட்டணம்.",
    catalogueSubtitle: "வெப்பத்தைப் பாதுகாக்கும் UV பாலிஹவுஸ் சோலார் உலர்த்திகளைப் பார்வையிடுங்கள். விவரக்குறிப்புகளுக்கு உலர்த்தியைக் கிளிக் செய்யவும்.",
    browseCapacity: "தினசரி திறன் அடிப்படையில் பார்க்க",
    browseCrop: "பயிர் வகை அடிப்படையில் பார்க்க",
    clickSpecs: "முழு விவரங்களுக்கு கிளிக் செய்க",
    targetAudienceLabel: "பயன்படுத்துபவர்",
    buildMaterialLabel: "தயாரிப்பு பொருள்",
    tempRangeLabel: "வெப்பநிலை வரம்பு",
    subsidyEligibilityLabel: "மானியத் தகுதி",
    viewSpecsPhotos: "விவரக்குறிப்புகள் & படங்கள் காண்க",
    checkSubsidyPricing: "மானியம் & விலை விவரம் அறிய",
    thSpecParam: "தொழில்நுட்ப அளவுரு",
    thPortable: "சிறிய கையடக்க உலர்த்தி",
    thPolyhouse: "வணிக பாலிஹவுஸ் உலர்த்தி",
    thIndustrial: "தொழில்முறை உலர்த்தி",
    stateAssistance: "மாநில அரசு மானிய உதவி",
    claimSubsidyTitle: "60% வரை அரசு மானியம் பெற விண்ணப்பியுங்கள்",
    claimSubsidyDesc: "நபார்டு மற்றும் மாநில விவசாய மானிய ஆவணங்களை நாங்கள் முழுமையாகச் செய்து தருகிறோம்.",
    checkSubsidyBtn: "மானியத் தகுதி அறிய",

    // Map Page & Component
    mapShowcaseBadge: "வரைபடப் பார்வை",
    mapTitle1: "செயலில் உள்ள சோலார் உலர்த்திகள்",
    mapTitle2: "தென்னிந்தியா முழுவதும்",
    mapSubtitle: "எங்கள் வரைபடத்தைப் பார்வையிட்டு நிறுவப்பட்ட இடங்கள் மற்றும் பயிர் உலர்த்தல் விவரங்களை அறிந்து கொள்ளுங்கள்.",
    filterStateLabel: "மாநில வடிப்பான்:",
    interactiveMapTab: "வரைபடம்",
    projectListTab: "திட்டப் பட்டியல்",
    visitTitle: "அருகிலுள்ள உலர்த்தியை நேரில் பார்வையிட வேண்டுமா?",
    visitDesc: "விவசாயிகள் மற்றும் FPO நிர்வாகிகளுக்கு நேரடி பண்ணைப் பார்வையிடலை ஏற்பாடு செய்கிறோம்.",
    bookVisitBtn: "நேரடி பார்வையிடலை முன்பதிவு செய்ய",

    // Footer
    footerAbout: "ஜெனிலெக் இந்தியாவில் உயர் திறன் கொண்ட பாலிஹவுஸ் சோலார் உலர்த்திகளை தயாரிக்கும் முன்னணி நிறுவனமாகும்.",
    footerDryerModels: "உலர்த்தி மாடல்கள்",
    footerDownloads: "பதிவிறக்கங்கள் & வழிகாட்டிகள்",
    footerCatalog: "தயாரிப்பு அட்டவணை (PDF)",
    footerSubsidyGuide: "அரசு மானிய வழிகாட்டி 2026",
    footerLabReport: "கொப்பரை ஆய்வக அறிக்கை",
    footerCoimbatoreFactory: "அலுவலகங்கள் & தொடர்பு",
    footerOffices: "அலுவலகங்கள் & தொடர்பு",
    footerRights: "அனைத்து உரிமைகளும் பாதுகாக்கப்பட்டவை.",
    footerPrivacy: "தனியுரிமைக் கொள்கை",
    footerTerms: "சேவை விதிகள்",

    // Crops
    cropCopra: "கொப்பரை / தேங்காய்",
    cropMoringa: "முருங்கை / மூலிகைகள் / தேயிலை",
    cropSpices: "மிளகாய் / மசாலாப் பொருட்கள்",
    cropFruits: "பழங்கள் & காய்கறிகள்",
    cropFish: "கருவாடு & கடல் உணவு",
    cropOther: "இதர பயிர்கள்",

    // Models
    modelPortable: "சிறிய கையடக்க சோலார் உலர்த்தி",
    modelPolyhouse: "வணிக பாலிஹவுஸ் சோலார் உலர்த்தி",
    modelIndustrial: "தொழில்முறை சோலார் உலர்த்தி"
  },

  hi: {
    announcement: "MNRE स्वीकृत एवं ISO 9001:2015 प्रमाणित | कारखाना: कोयंबटूर, तमिलनाडु",
    subsidyBadge: "40% - 60% सरकारी सब्सिडी योग्य",
    navHome: "होम",
    navAbout: "हमारे बारे में",
    navDryers: "सोलर ड्रायर",
    navApplications: "अनुप्रयोग",
    navGallery: "गैलरी",
    navStories: "किसान गाथाएं",
    navMap: "मानचित्र",
    navContact: "संपर्क करें",
    getQuote: "निःशुल्क कोटेशन पाएं",
    heroBadge: "अगली पीढ़ी की सोलर थर्मल खाद्य संरक्षण तकनीक",
    heroTitle1: "फसल के नुकसान को रोकें।",
    heroTitle2: "कृषि मुनाफा कई गुना बढ़ाएं।",
    heroSubtitle: "बिना बिजली बिल के प्राकृतिक रंग, सुगंध और पोषक तत्वों को सुरक्षित रखने वाला 100% सौर ऊर्जा संचालित ड्रायर।",
    calcSavings: "अपनी बचत की गणना करें",
    exploreModels: "सोलर ड्रायर मॉडल देखें",
    dryersInstalled: "स्थापित सोलर ड्रायर",
    foodSaved: "वार्षिक बचाई गई उपज",
    subsidyHelp: "सरकारी सब्सिडी सहायता",
    mnreBadge: "MNRE स्वीकृत उत्पाद",
    isoBadge: "ISO 9001:2015 गुणवत्ता प्रमाणित",
    subsidyBadge2: "100% राज्य सब्सिडी पात्रता",
    roiTitle: "लाभ एवं आकार कैलकुलेटर",
    roiSubtitle: "अपनी फसल और दैनिक मात्रा का चयन करके सुखाने की गति और बचत का अनुमान लगाएं।",
    selectCrop: "1. अपनी फसल / सामग्री चुनें",
    batchQty: "2. बैच उपज मात्रा (किग्रा)",
    sunDrying: "खुली धूप में सुखाना",
    solarDrying: "ZeniTEK सोलर ड्रायर",
    daysFaster: "दिन तेजी से सुखाना (सुरक्षित)",
    priceIncrease: "बाजार मूल्य वृद्धि %",
    profitPerBatch: "प्रति बैच अनुमानित लाभ व बचत",
    recSetup: "अनुशंसित मॉडल",
    getQuoteSetup: "कोटेशन प्राप्त करें",
    annualValueGain: "वार्षिक अनुमानित मूल्य वृद्धि (45 बैच)",
    estRoi: "अनुमानित निवेश का प्रतिफल (ROI)",
    modelsHeading: "अपने खेत के लिए सही सोलर ड्रायर चुनें",
    modelsSubtitle: "10 किग्रा घरेलू ड्रायर से लेकर 1 टन औद्योगिक प्लांट तक।",
    reqQuote: "मूल्य कोटेशन मांगें",
    whatCanYouDry: "ZeniTEK से आप क्या सुखा सकते हैं?",
    viewAllCrops: "सभी 50+ फसल सूची देखें",
    whyChooseUs: "ZeniTEK सोलर क्यों चुनें?",
    climateResilient: "मौसम प्रतिरोधी",
    climateDesc: "बादल वाले दिनों में भी निरंतर कार्य करता है।",
    zeroOpCost: "शून्य संचालन लागत",
    zeroOpDesc: "100% सौर ऊर्जा। कोई लकड़ी, कोयला या बिजली बिल नहीं।",
    hygienicSetup: "100% स्वच्छ प्रक्रिया",
    hygienicDesc: "धूल, कीड़ों और बारिश से पूर्ण सुरक्षा।",
    marketLinkage: "बाजार संबंध सहायता",
    marketDesc: "सूखे उत्पादों के लिए सीधे खरीदारों से जुड़ाव।",
    trustedBy: "1,200+ किसानों द्वारा विश्वसनीय",
    quickFormTitle: "व्हाट्सएप पर तुरंत मूल्य व सब्सिडी विवरण पाएं",
    quickFormDesc: "मूल्य व सब्सिडी की जानकारी के लिए 30 सेकंड का फॉर्म भरें।",
    yourName: "आपका नाम",
    whatsappNum: "व्हाट्सएप नंबर",
    districtCity: "राज्य / जिला",
    targetCrop: "फसल का प्रकार",
    getSubsidyQuote: "मूल्य व सब्सिडी कोटेशन पाएं",
    factoryLocation: "कार्यालय एवं संचालन केंद्र",
    callUs: "इंजीनियरिंग सहायता के लिए कॉल करें",
    emailUs: "बिक्री टीम को ईमेल करें",
    chatWhatsapp: "व्हाट्सएप पर तुरंत चैट करें",
    userCategory: "उपयोगकर्ता श्रेणी",
    desiredCapacity: "आवश्यक ड्रायर क्षमता",
    additionalReqs: "अतिरिक्त विवरण",
    submitProposal: "प्रस्ताव के लिए जमा करें",
    seeMoreDetails: "अधिक विवरण देखें",
    enquireSetup: "कोटेशन मांगें",
    projectDetails: "परियोजना विवरण",
    moistureReduction: "नमी का स्तर",
    close: "बंद करें",
    matrixModelBadge: "तकनीकी विनिर्देश तुलना",
    matrixModelTitle: "मॉडल तकनीकी तुलना तालिका",
    matrixModelSubtitle: "सभी ZeniTEK मॉडल की क्षमता, तापमान, निर्माण सामग्री और सरकारी सब्सिडी दिशानिर्देश।",
    matrixCropBadge: "फसल निर्जलीकरण प्रोफ़ाइल",
    matrixCropTitle: "फसल नमी पैरामीटर तालिका",
    matrixCropSubtitle: "नमी और सुखाने की अवधि की तुलना: ZeniTEK सोलर ड्रायर बनाम खुली धूप में सुखाना।",
    searchPlaceholder: "फसल या लाभ खोजें...",
    dryerModel: "ड्रायर मॉडल",
    descriptionReqs: "विवरण / अतिरिक्त आवश्यकताएं",
    getPricingSubsidyQuote: "मूल्य व सब्सिडी कोटेशन पाएं",

    // About Us Page
    aboutBadge: "ZeniTEK सोलर के बारे में",
    aboutTitle1: "किसानों का सशक्तिकरण।",
    aboutTitle2: "फसल बर्बादी का पूर्ण अंत।",
    aboutSubtitle: "कोयंबटूर में स्थित ZeniTEK विश्व स्तरीय पॉलीहाउस सोलर ड्रायर का निर्माण करता है।",
    aboutHub: "कोयंबटूर विनिर्माण केंद्र",
    aboutInnovation: "2 से अधिक दशकों का सोलर थर्मल नवाचार",
    aboutP1: "हमारा उद्देश्य कृषि बर्बादी को रोकना और किसानों को स्वच्छ सौर तकनीक उपलब्ध कराना है।",
    aboutP2: "हमारे 25,000 वर्ग फुट के कारखाने में उच्च गुणवत्ता वाले सोलर ड्रायर बनाए जाते हैं।",
    aboutF1: "✓ 25,000+ वर्ग फुट कारखाना",
    aboutF2: "✓ इन-हाउस थर्मल परीक्षण प्रयोगशाला",
    aboutPillarsTitle: "हमारे 3 तकनीकी स्तंभ",
    aboutPillarsSubtitle: "हमारे प्रत्येक ड्रायर में समाहित इंजीनियरिंग उत्कृष्टता।",
    pillar1Title: "अनुसंधान एवं नवाचार",
    pillar1Desc: "थर्मल स्टोरेज और यूवी पॉलीकार्बोनेट प्रकाश प्रवर्धन की तकनीक।",
    pillar2Title: "गुणवत्ता एवं मानक",
    pillar2Desc: "ISO 9001:2015 और CE सुरक्षा मानकों के अनुसार निर्माण।",
    pillar3Title: "कार्बन उत्सर्जन में कमी",
    pillar3Desc: "प्रतिवर्ष 15,000 मीट्रिक टन से अधिक CO₂ उत्सर्जन कम करना।",
    impact1: "किसान व FPO लाभान्वित",
    impact2: "फसल बर्बादी से बचाव",
    impact3: "किसान आय में वृद्धि",
    impact4: "सरकारी सब्सिडी सहायता",
    govtBadgesTitle: "सरकारी स्वीकृति एवं गुणवत्ता प्रमाण",
    mnreApproved: "MNRE स्वीकृत निर्माता",
    isoSystem: "ISO 9001:2015 गुणवत्ता प्रणाली",
    ceMarked: "CE प्रमाणित घटक",
    consultEngineers: "हमारे इंजीनियरों से परामर्श करें",

    // Applications Page
    appMatrixBadge: "विभिन्न फसल अनुप्रयोग तालिका",
    appMatrixTitle1: "50+ से अधिक कृषि उत्पादों को",
    appMatrixTitle2: "सुखाने के लिए निर्मित सोलर ड्रायर",
    appMatrixSubtitle: "पोषक तत्वों और प्राकृतिक स्वाद को बनाए रखने के लिए वैज्ञानिक सुखाने के तरीके।",
    tabAgri: "🌾 कृषि एवं भोजन (नारियल, सहजन, मसाले)",
    tabMarine: "🐟 समुद्री उत्पाद (सूखी मछली, झींगा)",
    tabIndustrial: "🏭 औद्योगिक उत्पाद (रबर, लकड़ी, अपशिष्ट)",
    thTargetProduce: "लक्ष्य उत्पाद",
    thFreshMoisture: "प्रारंभिक नमी %",
    thDriedMoisture: "अंतिम नमी %",
    thSolarTime: "ZeniTEK सोलर समय",
    thSunTime: "खुली धूप का समय",
    thProfitBenefit: "मुख्य लाभ",
    tailoredSolutions: "आपकी आवश्यकताओं के अनुसार समाधान",
    personaFpoTitle: "FPO और किसान समूहों के लिए",
    personaFpoDesc: "500 किग्रा+ दैनिक क्षमता वाले कम्युनिटी ड्रायर।",
    personaFpoBtn: "FPO प्रस्ताव मांगें →",
    personaExpTitle: "खाद्य निर्यातकों के लिए",
    personaExpDesc: "अंतरराष्ट्रीय मानकों के अनुरूप स्वचालित नमी नियंत्रक ड्रायर।",
    personaExpBtn: "निर्यात कोटेशन मांगें →",
    personaFarmerTitle: "छोटे किसानों के लिए",
    personaFarmerDesc: "40% सरकारी सब्सिडी के साथ किफ़ायती पोर्टेबल ड्रायर।",
    personaFarmerBtn: "किसान कोटेशन मांगें →",

    // Contact Us Page
    contactBadge: "सीधा कारखाना संपर्क",
    contactTitle1: "आइए आपके खेत के लिए सही",
    contactTitle2: "सोलर ड्रायर बनाएं।",
    contactSubtitle: "सब्सिडी और मूल्य की जानकारी के लिए हमारी टीम से संपर्क करें।",
    regOfficeLabel: "पंजीकृत कार्यालय (मुख्य पता)",
    regOfficeAddress: "4/501, Aitreya garden, Athappam palayam, Vallipurathanpalayam (PO), Erode (Dt), Tamil Nadu, PIN: 638 112",
    opOfficeLabel: "परिचालन कार्यालय",
    opOfficeAddress: "Zenitek Incubation center, SSM College of Engineering, NH-544, Valayakaranur, Komarapalayam, Namakkal Dt. - 638 183",
    gstinLabel: "GSTIN",
    gstinNumber: "33AACFZ8530G1Z5",
    primaryPhone: "+91-8903852623",
    primaryEmail: "zenitek2k@gmail.com",
    factoryAddressLabel: "पंजीकृत कार्यालय (मुख्य पता)",
    factoryAddressText: "4/501, Aitreya garden, Athappam palayam, Vallipurathanpalayam (PO), Erode (Dt), Tamil Nadu, PIN: 638 112",
    operationAddressLabel: "परिचालन कार्यालय",
    operationAddressText: "Zenitek Incubation center, SSM College of Engineering, NH-544, Valayakaranur, Komarapalayam, Namakkal Dt. - 638 183",
    workingHours: "सोम - शनि: सुबह 9:00 - शाम 7:00",
    preQualTitle: "मूल्य एवं सब्सिडी जांच फॉर्म",
    support1: "निःशुल्क सरकारी सब्सिडी योग्यता जांच",
    support2: "नमी विश्लेषण एवं आकार परामर्श",
    support3: "100% खेत पर स्थापना व प्रशिक्षण",
    csrBadge: "CSR एवं NGO भागीदारी पोर्टल",
    csrTitle: "ग्रामीण आजीविका परियोजनाओं के लिए हमारे साथ जुड़ें",
    csrDesc: "महिला स्वयं सहायता समूहों को सोलर ड्रायर प्रदान करने के लिए हम CSR के साथ काम करते हैं।",
    csrBtn: "CSR प्रस्ताव मांगें",

    // Farmer Stories Page
    storiesBadge: "किसान सफलता गाथाएं",
    storiesTitle1: "सच्ची कहानियां। वास्तविक समृद्धि।",
    storiesTitle2: "शून्य फसल बर्बादी।",
    storiesSubtitle: "उन किसानों के अनुभव जिन्होंने ZeniTEK के साथ अपनी आय बढ़ाई।",
    impactFamilies: "ग्रामीण परिवार लाभान्वित",
    impactValue: "कुल कृषक मूल्य संवर्धन",
    impactCrops: "बचाई गई फसलें",
    impactCleanEnergy: "100% स्वच्छ सौर ऊर्जा",
    videoReviewsTitle: "ग्राहक वीडियो समीक्षाएं",
    videoReviewsSub: "तमिलनाडु, केरल व महाराष्ट्र के किसानों के साक्षात्कार देखें।",
    caseStudiesTitle: "केस स्टडीज",
    pollachiCollective: "प Pollachi नारियल किसान समूह",
    pollachiTitle: "कैसे 50 किसानों ने बारिश का नुकसान रोककर आय में 28% की वृद्धि की?",
    probTitle: "समस्या",
    probDesc: "असामयिक बारिश से 30% नारियल खराब हो जाता था।",
    solTitle: "सोलर समाधान",
    solDesc: "50% सब्सिडी के साथ 500 किग्रा पॉलीहाउस सोलर ड्रायर लगाया गया।",
    resTitle: "परिणाम",
    resDesc: "2.5 दिनों में 100% सफेद कोपरा तैयार। ₹18/किग्रा अतिरिक्त लाभ।",
    commitmentTitle: "हमारी 360° ग्राहक सेवा प्रतिबद्धता",
    comm1Title: "पूर्ण सब्सिडी सहायता",
    comm1Desc: "हम सभी सरकारी सब्सिडी और बैंक ऋण की कागजी कार्रवाई संभालते हैं।",
    comm2Title: "स्थापना व ऑन-फार्म प्रशिक्षण",
    comm2Desc: "हमारे इंजीनियर आपके खेत में ड्रायर स्थापित कर प्रशिक्षण प्रदान करते हैं।",
    comm3Title: "सीधा बाजार संबंध",
    comm3Desc: "हम किसानों को प्रमाणित कारपोरेट खरीदारों से जोड़ते हैं।",
    startProsperityBtn: "आज ही अपनी सफलता की शुरुआत करें",

    // Gallery Page
    galleryBadge: "परियोजना व उत्पाद गैलरी",
    galleryTitle1: "ZeniTEK सोलर ड्रायर",
    galleryTitle2: "एवं सूखे उत्पादों की तस्वीरें",
    gallerySubtitle: "तमिलनाडु, केरल, आंध्र प्रदेश और कर्नाटक में स्थापित ड्रायर और गुणवत्तापूर्ण सूखे उत्पाद।",
    catAll: "सभी तस्वीरें",
    catInstallations: "खेत स्थापनाएं",
    catProduce: "सूखे उत्पाद की गुणवत्ता",
    catModels: "ड्रायर मॉडल",
    catFactory: "कारखाना व असेंबली",
    viewEnlarged: "बड़ी तस्वीर देखें",
    clickFullSpec: "पूर्ण विवरण के लिए क्लिक करें",
    customDryerBadge: "अपना सोलर ड्रायर प्राप्त करें",
    customDryerTitle: "क्या आप भी ऐसा सोलर ड्रायर स्थापित करना चाहते हैं?",
    customDryerDesc: "हम 40%-60% सब्सिडी सहायता के साथ सोलर ड्रायर स्थापित करते हैं।",
    locationLabel: "स्थान:",
    requestQuoteForModel: "इस मॉडल के लिए कोटेशन मांगें",

    // Solar Dryers Page
    catalogueBadge: "सोलर ड्रायर कैटलॉग",
    catalogueTitle1: "100% सौर ऊर्जा सुखाने की तकनीक।",
    catalogueTitle2: "5 गुना तेज। शून्य बिजली बिल।",
    catalogueSubtitle: "अधिकतम तापमान बनाए रखने वाले पॉलीहाउस सोलर ड्रायर देखें। विनिर्देशों के लिए मॉडल पर क्लिक करें।",
    browseCapacity: "क्षमता अनुसार देखें",
    browseCrop: "फसल प्रकार अनुसार देखें",
    clickSpecs: "पूर्ण विनिर्देशों के लिए क्लिक करें",
    targetAudienceLabel: "उपयोगकर्ता",
    buildMaterialLabel: "निर्माण सामग्री",
    tempRangeLabel: "तापमान सीमा",
    subsidyEligibilityLabel: "सब्सिडी पात्रता",
    viewSpecsPhotos: "विनिर्देश व तस्वीरें देखें",
    checkSubsidyPricing: "मूल्य व सब्सिडी जांचें",
    thSpecParam: "तकनीकी पैरामीटर",
    thPortable: "पोर्टेबल घरेलू ड्रायर",
    thPolyhouse: "कमर्शियल पॉलीहाउस",
    thIndustrial: "औद्योगिक मल्टी-टनल",
    stateAssistance: "राज्य सरकार सब्सिडी सहायता",
    claimSubsidyTitle: "अपने सोलर ड्रायर पर 60% तक सब्सिडी प्राप्त करें",
    claimSubsidyDesc: "हम NABARD और राज्य कृषि सब्सिडी कागजी कार्रवाई में पूरी सहायता प्रदान करते हैं।",
    checkSubsidyBtn: "सब्सिडी पात्रता जांचें",

    // Map Page & Component
    mapShowcaseBadge: "भौगोलिक कार्य प्रदर्शन",
    mapTitle1: "सक्रिय सोलर ड्रायर इकाइयां",
    mapTitle2: "दक्षिण भारत एवं अन्य क्षेत्रों में",
    mapSubtitle: "मानचित्र पर हमारे स्थापित सोलर ड्रायर और उनके परिणामों को देखें।",
    filterStateLabel: "राज्य चुनें:",
    interactiveMapTab: "मानचित्र",
    projectListTab: "परियोजना सूची",
    visitTitle: "क्या आप निकटतम सोलर ड्रायर इकाई देखना चाहते हैं?",
    visitDesc: "हम किसानों और अधिकारियों के लिए लाइव साइट विजिट आयोजित करते हैं।",
    bookVisitBtn: "साइट विजिट बुक करें",

    // Footer
    footerAbout: "ZeniTEK भारत में उच्च क्षमता वाले पॉलीहाउस सोलर थर्मल ड्रायर का अग्रणी निर्माता है।",
    footerDryerModels: "सोलर ड्रायर मॉडल",
    footerDownloads: "डाउनलोड व गाइड",
    footerCatalog: "उत्पाद कैटलॉग (PDF)",
    footerSubsidyGuide: "सरकारी सब्सिडी गाइड 2026",
    footerLabReport: "कोपरा लैब परीक्षण रिपोर्ट",
    footerCoimbatoreFactory: "कार्यालय एवं संचालन",
    footerOffices: "कार्यालय एवं संचालन",
    footerRights: "सर्वाधिकार सुरक्षित।",
    footerPrivacy: "गोपनीयता नीति",
    footerTerms: "सेवा की शर्तें",

    // Crops
    cropCopra: "कोपरा / नारियल",
    cropMoringa: "सहजन / जड़ी-बूटियां / चाय",
    cropSpices: "लाल मिर्च / मसाले",
    cropFruits: "फल एवं सब्जियां",
    cropFish: "सूखी मछली व समुद्री भोजन",
    cropOther: "अन्य फसलें",

    // Models
    modelPortable: "पोर्टेबल DIY सोलर ड्रायर",
    modelPolyhouse: "कमर्शियल पॉलीहाउस सोलर ड्रायर",
    modelIndustrial: "औद्योगिक मल्टी-टनल सोलर ड्रायर"
  },

  ml: {
    announcement: "MNRE അംഗീകൃത & ISO 9001:2015 സർട്ടിഫൈഡ് | ഫാക്ടറി: കോയമ്പത്തൂർ",
    subsidyBadge: "40% - 60% സർക്കാർ സബ്സിഡി ലഭ്യം",
    navHome: "ഹോം",
    navAbout: "ഞങ്ങളെക്കുറിച്ച്",
    navDryers: "സോളാർ ഡ്രയറുകൾ",
    navApplications: "ഉപയോഗങ്ങൾ",
    navGallery: "ഗ്യാലറി",
    navStories: "കർഷക കഥകൾ",
    navMap: "മാപ്പ്",
    navContact: "ബന്ധപ്പെടുക",
    getQuote: "സൗജന്യ വിലവിവരം നേടൂ",
    heroBadge: "അത്യാധുനിക സോളാർ തെർമൽ ഉണക്കൽ സാങ്കേതികവിദ്യ",
    heroTitle1: "വിളനാശം തടയൂ.",
    heroTitle2: "കാർഷിക ലാഭം വർദ്ധിപ്പിക്കൂ.",
    heroSubtitle: "വൈദ്യുതി ബില്ലില്ലാതെ ഗുണമേന്മയും മണവും നിറവും നിലനിർത്തുന്ന 100% സോളാർ ഡ്രയറുകൾ.",
    calcSavings: "ലാഭം കണക്കാക്കൂ",
    exploreModels: "മോഡലുകൾ കാണുക",
    dryersInstalled: "സ്ഥാപിച്ച ഡ്രയറുകൾ",
    foodSaved: "സംരക്ഷിച്ച ഭക്ഷണം/വർഷം",
    subsidyHelp: "സർക്കാർ സബ്സിഡി സഹായം",
    mnreBadge: "MNRE അംഗീകൃത ഡ്രയർ",
    isoBadge: "ISO 9001:2015 സർട്ടിഫൈഡ്",
    subsidyBadge2: "100% സംസ്ഥാന സബ്സിഡി അർഹത",
    roiTitle: "ലാഭവും അളവും കണക്കാക്കാം",
    roiSubtitle: "നിങ്ങളുടെ വിളയും അളവും തിരഞ്ഞെടുത്ത് ഉണങ്ങുന്ന സമയവും ലാഭവും കണക്കാക്കൂ.",
    selectCrop: "1. വിള തിരഞ്ഞെടുക്കുക",
    batchQty: "2. അളവ് (കിലോ)",
    sunDrying: "തുറസ്സായ വെയിലിൽ ഉണക്കൽ",
    solarDrying: "ZeniTEK സോളാർ ഡ്രയർ",
    daysFaster: "ദിവസങ്ങൾ വേഗത്തിൽ ഉണങ്ങുന്നു",
    priceIncrease: "വിപണി വില വർദ്ധനവ് %",
    profitPerBatch: "പ്രതീക്ഷിക്കുന്ന ലാഭം",
    recSetup: "അനുയോജ്യമായ മോഡൽ",
    getQuoteSetup: "വിലവിവരം നേടുക",
    annualValueGain: "പ്രതീക്ഷിക്കുന്ന വാർഷിക ലാഭം (45 ബാച്ച്)",
    estRoi: "പ്രതീക്ഷിക്കുന്ന നിക്ഷേപ ലാഭം (ROI)",
    modelsHeading: "നിങ്ങളുടെ ആവശ്യത്തിനനുസരിച്ചുള്ള സോളാർ ഡ്രയറുകൾ",
    modelsSubtitle: "10 കിലോ ഗാർഹിക ഡ്രയർ മുതൽ 1 ടൺ വ്യവസായ ഡ്രയർ വരെ.",
    reqQuote: "വിലവിവരം ചോദിക്കൂ",
    whatCanYouDry: "സെനിടെക് ഉപയോഗിച്ച് എന്തൊക്കെ ഉണക്കാം?",
    viewAllCrops: "എല്ലാ 50+ വിളകളുടെ പട്ടിക കാണുക",
    whyChooseUs: "എന്തുകൊണ്ട് സെനിടെക് സോളാർ?",
    climateResilient: "കാലാവസ്ഥയെ ചെറുക്കുന്നു",
    climateDesc: "മേഘാവൃതമായ ദിവസങ്ങളിലും ചൂട് നിലനിർത്തുന്നു.",
    zeroOpCost: "സീറോ പ്രവർത്തന ചിലവ്",
    zeroOpDesc: "100% സൂര്യപ്രകാശം. വിറകോ കറന്റ് ബില്ലോ ഇല്ല.",
    hygienicSetup: "100% ശുചിത്വമുള്ള ഉണക്കൽ",
    hygienicDesc: "പൊടി, പ്രാണികൾ, മഴ എന്നിവയിൽ നിന്ന് പൂർണ്ണ സംരക്ഷണം.",
    marketLinkage: "വിപണി സഹായം",
    marketDesc: "ഉണക്കിയ ഉൽപ്പന്നങ്ങൾക്ക് നേരിട്ടുള്ള വിപണി ബന്ധം.",
    trustedBy: "1,200+ കർഷകർ വിശ്വസിക്കുന്നു",
    quickFormTitle: "വാട്സാപ്പിൽ വിലവിവരങ്ങളും സബ്സിഡിയും അറിയൂ",
    quickFormDesc: "വിവരങ്ങൾക്ക് 30 സെക്കൻഡ് ഫോം പൂരിപ്പിക്കൂ.",
    yourName: "നിങ്ങളുടെ പേര്",
    whatsappNum: "വാട്സാപ്പ് നമ്പർ",
    districtCity: "സംസ്ഥാനം / ജില്ല",
    targetCrop: "ഉണക്കേണ്ട വിള",
    getSubsidyQuote: "വിലവിവരങ്ങളും സബ്സിഡിയും നേടൂ",
    factoryLocation: "ഓഫീസുകൾ & പ്രവർത്തനങ്ങൾ",
    callUs: "എഞ്ചിനീയറിംഗ് സഹായത്തിന് വിളിക്കൂ",
    emailUs: "സെയിൽസ് ടീമിന് ഇമെയിൽ അയക്കൂ",
    chatWhatsapp: "വാട്സാപ്പിൽ മെസ്സേജ് അയക്കൂ",
    userCategory: "വിഭാഗം",
    desiredCapacity: "ആവശ്യമായ ശേഷി",
    additionalReqs: "കൂടുതൽ വിവരങ്ങൾ",
    submitProposal: "വിവരങ്ങൾ അയക്കൂ",
    seeMoreDetails: "കൂടുതൽ വിവരങ്ങൾ കാണുക",
    enquireSetup: "അന്വേഷിക്കുക",
    projectDetails: "പദ്ധതി വിവരങ്ങൾ",
    moistureReduction: "ഈർപ്പത്തിന്റെ അളവ്",
    close: "അടയ്ക്കുക",
    matrixModelBadge: "സാങ്കേതിക സവിശേഷതകളുടെ താരതമ്യം",
    matrixModelTitle: "മോഡൽ സാങ്കേതിക താരതമ്യ പട്ടിക",
    matrixModelSubtitle: "എല്ലാ സെനിടെക് ഡ്രയർ മോഡലുകളുടെയും ശേഷി, താപനില, നിർമ്മാണ സാമഗ്രികൾ, സർക്കാർ സബ്സിഡി വിവരങ്ങൾ.",
    matrixCropBadge: "വിള ഉണക്കൽ വിവരങ്ങൾ",
    matrixCropTitle: "വിള ഈർപ്പത്തിന്റെ അളവുകോൽ പട്ടിക",
    matrixCropSubtitle: "ഈർപ്പവും ഉണങ്ങുന്ന സമയവും തമ്മിലുള്ള താരതമ്യം: സെനിടെക് സോളാർ ഡ്രയർ വിഎസ് തുറസ്സായ വെയിൽ.",
    searchPlaceholder: "വിളയോ പ്രയോജനങ്ങളോ തിരയൂ...",
    dryerModel: "ഡ്രയർ മോഡൽ",
    descriptionReqs: "വിവരണം / കൂടുതൽ ആവശ്യങ്ങൾ",
    getPricingSubsidyQuote: "വിലവിവരങ്ങളും സബ്സിഡിയും നേടൂ",

    // About Us Page
    aboutBadge: "സെനിടെക് സോളാറിനെക്കുറിച്ച്",
    aboutTitle1: "കർഷക ശാക്തീകരണം.",
    aboutTitle2: "വിളനാശം പൂർണ്ണമായി തടയൽ.",
    aboutSubtitle: "കോയമ്പത്തൂർ ആസ്ഥാനമായുള്ള സെനിടെക് അന്താരാഷ്ട്ര നിലവാരമുള്ള പോളിഹൗസ് സോളാർ ഡ്രയറുകൾ നിർമ്മിക്കുന്നു.",
    aboutHub: "കോയമ്പത്തൂർ നിർമ്മാണ കേന്ദ്രം",
    aboutInnovation: "2 ദശാബ്ദത്തിലേറെ സോളാർ തെർമൽ പരിചയം",
    aboutP1: "കാർഷിക നാശം തടഞ്ഞ് സൗരോർജ്ജ സാങ്കേതികവിദ്യ കർഷകരിലേക്ക് എത്തിക്കുക എന്നതാണ് ഞങ്ങളുടെ ലക്ഷ്യം.",
    aboutP2: "25,000 ചതുരശ്ര അടി ഫാക്ടറിയിൽ മികച്ച ഗുണനിലവാരത്തോടെ ഡ്രയറുകൾ നിർമ്മിക്കപ്പെടുന്നു.",
    aboutF1: "✓ 25,000+ ചതുരശ്ര അടി ഫാക്ടറി",
    aboutF2: "✓ ഓൺ-സൈറ്റ് പരിശോധനാ ലാബ്",
    aboutPillarsTitle: "ഞങ്ങളുടെ 3 സാങ്കേതിക തൂണുകൾ",
    aboutPillarsSubtitle: "ഓരോ ഡ്രയറിലുമുള്ള മികച്ച എഞ്ചിനീയറിംഗ് മികവ്.",
    pillar1Title: "ഗവേഷണവും വികസനവും",
    pillar1Desc: "താപ ശേഖരണവും യുവി പോളിഹൗസ് വെളിച്ച നിയന്ത്രണ സാങ്കേതികവിദ്യയും.",
    pillar2Title: "ഗുണനിലവാര നിലവാരം",
    pillar2Desc: "ISO 9001:2015, CE സർട്ടിഫിക്കേഷനുകൾക്ക് അനുസരിച്ചുള്ള നിർമ്മാണം.",
    pillar3Title: "കാർബൺ മലിനീകരണം കുറയ്ക്കൽ",
    pillar3Desc: "വർഷത്തിൽ 15,000 ടണ്ണിലധികം CO₂ മലിനീകരണം കുറയ്ക്കുന്നു.",
    impact1: "കർഷകരും FPO-കളും",
    impact2: "സംരക്ഷിച്ച ഭക്ഷണം",
    impact3: "കർഷക വരുമാന വർദ്ധനവ്",
    impact4: "സബ്സിഡി സഹായം",
    govtBadgesTitle: "സർക്കാർ അംഗീകാരങ്ങൾ",
    mnreApproved: "MNRE അംഗീകൃത നിർമ്മാതാവ്",
    isoSystem: "ISO 9001:2015 സിസ്റ്റം",
    ceMarked: "CE അംഗീകൃത ഭാഗങ്ങൾ",
    consultEngineers: "എഞ്ചിനീയർമാരുമായി സംസാരിക്കൂ",

    // Applications Page
    appMatrixBadge: "വിവിധ വിള ഉപയോഗ പട്ടിക",
    appMatrixTitle1: "50-ലധികം കാർഷിക ഉൽപ്പന്നങ്ങൾ",
    appMatrixTitle2: "ഉണക്കാൻ കഴിയുന്ന സോളാർ ഡ്രയറുകൾ",
    appMatrixSubtitle: "ഗുണമേന്മയും മണവും നിലനിർത്താൻ സഹായിക്കുന്ന ഉണക്കൽ രീതികൾ.",
    tabAgri: "🌾 കൃഷിയും ഭക്ഷണവും (കൊപ്ര, മുരിങ്ങ, സുഗന്ധവ്യഞ്ജനങ്ങൾ)",
    tabMarine: "🐟 കടൽ വിഭവങ്ങൾ (ഉണക്കമീൻ, ചെമ്മീൻ)",
    tabIndustrial: "🏭 വ്യവസായ ഉൽപ്പന്നങ്ങൾ (റബ്ബർ, മരം, വേസ്റ്റുകൾ)",
    thTargetProduce: "ഉൽപ്പന്നം",
    thFreshMoisture: "ആദ്യ ഈർപ്പം %",
    thDriedMoisture: "അവസാന ഈർപ്പം %",
    thSolarTime: "സെനിടെക് സമയം",
    thSunTime: "സാധാരണ സമയം",
    thProfitBenefit: "പ്രധാന ലാഭം",
    tailoredSolutions: "നിങ്ങളുടെ ആവശ്യങ്ങൾക്കനുസരിച്ചുള്ള പരിഹാരങ്ങൾ",
    personaFpoTitle: "FPO കളും സൊസൈറ്റികളും",
    personaFpoDesc: "500 കിലോയിലധികം വലിയ അളവുകൾ ഉണക്കാനുള്ള ഡ്രയറുകൾ.",
    personaFpoBtn: "FPO ഓഫർ നേടൂ →",
    personaExpTitle: "കയറ്റുമതിക്കാർക്ക്",
    personaExpDesc: "അന്താരാഷ്ട്ര നിലവാരമുള്ള ഓട്ടോമാറ്റിക് ഡ്രയറുകൾ.",
    personaExpBtn: "കയറ്റുമതി ഓഫർ നേടൂ →",
    personaFarmerTitle: "ചെറുകിട കർഷകർക്ക്",
    personaFarmerDesc: "40% സർക്കാർ സബ്സിഡിയുള്ള ഗാർഹിക ഡ്രയറുകൾ.",
    personaFarmerBtn: "കർഷക ഓഫർ നേടൂ →",

    // Contact Us Page
    contactBadge: "നേരിട്ടുള്ള ഫാക്ടറി ബന്ധം",
    contactTitle1: "നിങ്ങളുടെ ആവശ്യത്തിനനുസരിച്ചുള്ള",
    contactTitle2: "സോളാർ ഡ്രയർ നിർമ്മിക്കാം.",
    contactSubtitle: "വിലവിവരങ്ങൾക്കും സബ്സിഡിക്കുമായി ഞങ്ങളുടെ ടീമുമായി ബന്ധപ്പെടൂ.",
    regOfficeLabel: "രജിസ്റ്റേർഡ് ഓഫീസ് (പ്രധാന വിലാസം)",
    regOfficeAddress: "4/501, Aitreya garden, Athappam palayam, Vallipurathanpalayam (PO), Erode (Dt), Tamil Nadu, PIN: 638 112",
    opOfficeLabel: "ഓപ്പറേഷൻ വിലാസം",
    opOfficeAddress: "Zenitek Incubation center, SSM College of Engineering, NH-544, Valayakaranur, Komarapalayam, Namakkal Dt. - 638 183",
    gstinLabel: "GSTIN",
    gstinNumber: "33AACFZ8530G1Z5",
    primaryPhone: "+91-8903852623",
    primaryEmail: "zenitek2k@gmail.com",
    factoryAddressLabel: "രജിസ്റ്റേർഡ് ഓഫീസ് (പ്രധാന വിലാസം)",
    factoryAddressText: "4/501, Aitreya garden, Athappam palayam, Vallipurathanpalayam (PO), Erode (Dt), Tamil Nadu, PIN: 638 112",
    operationAddressLabel: "ഓപ്പറേഷൻ വിലാസം",
    operationAddressText: "Zenitek Incubation center, SSM College of Engineering, NH-544, Valayakaranur, Komarapalayam, Namakkal Dt. - 638 183",
    workingHours: "തിങ്കൾ - ശനി: 9:00 AM - 7:00 PM",
    preQualTitle: "വില വിവരങ്ങൾ ചോദിച്ചറിയാം",
    support1: "സൗജന്യ സബ്സിഡി യോഗ്യതാ പരിശോധന",
    support2: "ഈർപ്പ പരിശോധന സഹായം",
    support3: "100% ഇൻസ്റ്റാളേഷൻ സഹായവും പരിശീലനവും",
    csrBadge: "CSR & NGO പങ്കാളിത്തം",
    csrTitle: "ഗ്രാമീണ വികസന പദ്ധതികൾക്കായി ഞങ്ങളോടൊപ്പം ചേരൂ",
    csrDesc: "വനിതാ കൂട്ടായ്മകൾക്ക് ഡ്രയറുകൾ നൽകാൻ CSR ഫണ്ടുകളുമായി സഹകരിക്കുന്നു.",
    csrBtn: "CSR വിവരങ്ങൾ നേടൂ",

    // Farmer Stories Page
    storiesBadge: "കർഷക വിജയഗാഥകൾ",
    storiesTitle1: "യഥാർത്ഥ അനുഭവങ്ങൾ. യഥാർത്ഥ വളർച്ച.",
    storiesTitle2: "വിളനാശമില്ലാത്ത കൃഷി.",
    storiesSubtitle: "സെനിടെക് ഉപയോഗിച്ച് ലാഭം കൂട്ടിയ കർഷകരുടെ അനുഭവങ്ങൾ.",
    impactFamilies: "ബോധവൽക്കരിക്കപ്പെട്ട കർഷകർ",
    impactValue: "കർഷകർക്ക് ലഭിച്ച അധിക ലാഭം",
    impactCrops: "സംരക്ഷിച്ച വിളകൾ",
    impactCleanEnergy: "100% സൗരോർജ്ജം",
    videoReviewsTitle: "ഉപഭോക്തൃ വീഡിയോ അഭിപ്രായങ്ങൾ",
    videoReviewsSub: "കേരളം, തമിഴ്നാട്, മഹാരാഷ്ട്ര എന്നിവിടങ്ങളിലെ കർഷകരുടെ വീഡിയോകൾ.",
    caseStudiesTitle: "കേസ് സ്റ്റഡികൾ",
    pollachiCollective: "പൊള്ളാച്ചി നാളികേര കർഷക സമിതി",
    pollachiTitle: "50 കർഷകർ മഴക്കെടുതി തടഞ്ഞ് വരുമാനം 28% വർദ്ധിപ്പിച്ചതെങ്ങനെ?",
    probTitle: "പ്രശ്നം",
    probDesc: "മഴ കാരണം 30% കൊപ്ര പൂപ്പൽ പിടിച്ച് നശിച്ചു.",
    solTitle: "പരിഹാരം",
    solDesc: "50% സബ്സിഡിയോടെ 500 കിലോ പോളിഹൗസ് സോളാർ ഡ്രയർ സ്ഥാപിച്ചു.",
    resTitle: "ഫലം",
    resDesc: "2.5 ദിവസം കൊണ്ട് ഒന്നാം തരം വെളുത്ത കൊപ്ര. കിലോയ്ക്ക് ₹18 അധിക ലാഭം.",
    commitmentTitle: "ഞങ്ങളുടെ 360° പിന്തുണ വാഗ്ദാനം",
    comm1Title: "പൂർണ്ണ സബ്സിഡി സഹായം",
    comm1Desc: "ബാങ്ക് വായ്പകളും സബ്സിഡി അപേക്ഷകളും ഞങ്ങൾ ചെയ്തു നൽകുന്നു.",
    comm2Title: "ഇൻസ്റ്റാളേഷൻ & പരിശീലനം",
    comm2Desc: "ഞങ്ങളുടെ എഞ്ചിനീയർമാർ ഫാക്ടറിയിൽ നിന്ന് നേരിട്ടെത്തി പരിശീലനം നൽകുന്നു.",
    comm3Title: "വിപണി ബന്ധം",
    comm3Desc: "ഉൽപന്നങ്ങൾക്ക് നേരിട്ടുള്ള വിപണി ബന്ധം നൽകുന്നു.",
    startProsperityBtn: "നിങ്ങളുടെ വിജയഗാഥ ഇന്ന് തന്നെ തുടങ്ങൂ",

    // Gallery Page
    galleryBadge: "ചിത്രങ്ങളും പ്രോജക്ടുകളും",
    galleryTitle1: "സെനിടെക് സോളാർ ഡ്രയർ",
    galleryTitle2: "ഉൽപ്പന്ന ചിത്രങ്ങൾ",
    gallerySubtitle: "കേരളം, തമിഴ്നാട്, കർണാടക എന്നിവിടങ്ങളിൽ സ്ഥാപിച്ച ഡ്രയറുകളുടെ ചിത്രങ്ങൾ.",
    catAll: "എല്ലാ ചിത്രങ്ങളും",
    catInstallations: "സ്ഥാപിച്ച സ്ഥലങ്ങൾ",
    catProduce: "ഉണക്കിയ ഉൽപ്പന്നങ്ങൾ",
    catModels: "ഡ്രയർ മോഡലുകൾ",
    catFactory: "ഫാക്ടറി",
    viewEnlarged: "വലുതായി കാണുക",
    clickFullSpec: "വിശദാംശങ്ങൾക്ക് ക്ലിക്ക് ചെയ്യൂ",
    customDryerBadge: "നിങ്ങളുടെ സോളാർ ഡ്രയർ നേടൂ",
    customDryerTitle: "ഇതുപോലൊരു സോളാർ ഡ്രയർ നിങ്ങൾക്കും വേണോ?",
    customDryerDesc: "40%-60% സബ്സിഡിയോടെ ഡ്രയറുകൾ നിർമ്മിച്ച് നൽകുന്നു.",
    locationLabel: "സ്ഥലം:",
    requestQuoteForModel: "ഈ മോഡലിന്റെ വില അറിയൂ",

    // Solar Dryers Page
    catalogueBadge: "സോളാർ ഡ്രയർ കാറ്റലോഗ്",
    catalogueTitle1: "100% സൗരോർജ്ജ ഡ്രയറുകൾ.",
    catalogueTitle2: "5 മടങ്ങ് വേഗത. സീറോ കറന്റ് ബിൽ.",
    catalogueSubtitle: "വിവിധ തരം ഡ്രയർ മോഡലുകൾ കാണുക. കൂടുതൽ വിവരങ്ങൾക്ക് ക്ലിക്ക് ചെയ്യൂ.",
    browseCapacity: "ശേഷി അനുസരിച്ച്",
    browseCrop: "വിളകൾ അനുസരിച്ച്",
    clickSpecs: "വിശദാംശങ്ങൾക്ക് ക്ലിക്ക് ചെയ്യൂ",
    targetAudienceLabel: "ആർക്കൊക്കെ ഉപയോഗിക്കാം",
    buildMaterialLabel: "നിർമ്മാണ സാമഗ്രികൾ",
    tempRangeLabel: "താപനില",
    subsidyEligibilityLabel: "സബ്സിഡി അർഹത",
    viewSpecsPhotos: "വിവരങ്ങളും ചിത്രങ്ങളും കാണുക",
    checkSubsidyPricing: "വിലയും സബ്സിഡിയും അറിയൂ",
    thSpecParam: "സാങ്കേതിക വിവരങ്ങൾ",
    thPortable: "പോർട്ടബിൾ ഡ്രയർ",
    thPolyhouse: "കമേഴ്സ്യൽ പോളിഹൗസ്",
    thIndustrial: "ഇൻഡസ്ട്രിയൽ ഡ്രയർ",
    stateAssistance: "സംസ്ഥാന സർക്കാർ സബ്സിഡി സഹായം",
    claimSubsidyTitle: "60% വരെ സർക്കാർ സബ്സിഡി നേടൂ",
    claimSubsidyDesc: "പേപ്പർ വർക്കുകളും സബ്സിഡി നടപടികളും ഞങ്ങൾ ചെയ്ത് നൽകുന്നു.",
    checkSubsidyBtn: "സബ്സിഡി യോഗ്യത അറിയൂ",

    // Map Page & Component
    mapShowcaseBadge: "മാപ്പ് വിവരങ്ങൾ",
    mapTitle1: "പ്രവർത്തിക്കുന്ന സോളാർ ഡ്രയറുകൾ",
    mapTitle2: "ദക്ഷിണേന്ത്യയിലുടനീളം",
    mapSubtitle: "ഞങ്ങളുടെ ഡ്രയറുകൾ സ്ഥാപിച്ച സ്ഥലങ്ങളും വിശദാംശങ്ങളും മാപ്പിൽ കാണുക.",
    filterStateLabel: "സംസ്ഥാനം:",
    interactiveMapTab: "മാപ്പ്",
    projectListTab: "പട്ടിക",
    visitTitle: "അടുത്തുള്ള ഡ്രയർ നേരിട്ട് കാണണോ?",
    visitDesc: "കർഷകർക്കായി ഞങ്ങൾ സന്ദർശന സൗകര്യം ഒരുക്കുന്നു.",
    bookVisitBtn: "ബുക്ക് ചെയ്യൂ",

    // Footer
    footerAbout: "ഉയർന്ന ശേഷിയുള്ള സോളാർ ഡ്രയറുകൾ നിർമ്മിക്കുന്ന ഇന്ത്യയിലെ മുൻനിര സ്ഥാപനം.",
    footerDryerModels: "ഡ്രയർ മോഡലുകൾ",
    footerDownloads: "ഡൗൺലോഡുകൾ",
    footerCatalog: "പ്രൊഡക്ട് കാറ്റലോഗ് (PDF)",
    footerSubsidyGuide: "സബ്സിഡി ഗൈഡ് 2026",
    footerLabReport: "കൊപ്ര ടെസ്റ്റ് റിപ്പോർട്ട്",
    footerCoimbatoreFactory: "ഓഫീസുകൾ & ബന്ധപ്പെടാൻ",
    footerOffices: "ഓഫീസുകൾ & ബന്ധപ്പെടാൻ",
    footerRights: "എല്ലാ അവകാശങ്ങളും സംരക്ഷിതം.",
    footerPrivacy: "സ്വകാര്യതാ നയം",
    footerTerms: "നിബന്ധനകൾ",

    // Crops
    cropCopra: "കൊപ്ര / തേങ്ങ",
    cropMoringa: "മുരിങ്ങ / സുഗന്ധവ്യഞ്ജനങ്ങൾ",
    cropSpices: "മുളക് / കുരുമുളക്",
    cropFruits: "പഴങ്ങളും പച്ചക്കറികളും",
    cropFish: "ഉണക്കമീൻ / ചെമ്മീൻ",
    cropOther: "മറ്റ് വിളകൾ",

    // Models
    modelPortable: "പോർട്ടബിൾ സോളാർ ഡ്രയർ",
    modelPolyhouse: "പോളിഹൗസ് സോളാർ ഡ്രയർ",
    modelIndustrial: "ഇൻഡസ്ട്രിയൽ സോളാർ ഡ്രയർ"
  },

  te: {
    announcement: "MNRE గుర్తింపు పొందినది & ISO 9001:2015 సర్టిఫైడ్ | ఫ్యాక్టరీ: కోయంబత్తూర్",
    subsidyBadge: "40% - 60% ప్రభుత్వ సబ్సిడీ అర్హత",
    navHome: "హోమ్",
    navAbout: "మా గురించి",
    navDryers: "సోలార్ డ్రైయర్లు",
    navApplications: "ఉపయోగాలు",
    navGallery: "గ్యాలరీ",
    navStories: "రైతు కథలు",
    navMap: "మ్యాప్",
    navContact: "సంప్రదించండి",
    getQuote: "ఉచిత కొటేషన్ పొందండి",
    heroBadge: "నెక్స్ట్-జెన్ సోలార్ థర్మల్ ఆహార పరిరక్షణ సాంకేతికత",
    heroTitle1: "పంట నష్టాన్ని నివారించండి.",
    heroTitle2: "వ్యవసాయ లాభాలను రెట్టింపు చేయండి.",
    heroSubtitle: "కరెంట్ బిల్లు లేకుండా రంగు, రుచి, పోషకాలను కాపాడే 100% సౌరశక్తి డ్రైయర్.",
    calcSavings: "లాభాన్ని లెక్కించండి",
    exploreModels: "డ్రైయర్ మోడల్స్ చూడండి",
    dryersInstalled: "ఏర్పాటు చేసిన డ్రైయర్లు",
    foodSaved: "సంవత్సరానికి కాపాడిన పంట",
    subsidyHelp: "ప్రభుత్వ సబ్సిడీ సహాయం",
    mnreBadge: "MNRE ఆమోదించిన మోడల్",
    isoBadge: "ISO 9001:2015 సర్టిఫైడ్ క్వాలిటీ",
    subsidyBadge2: "100% రాష్ట్ర సబ్సిడీ అర్హత",
    roiTitle: "లాభం మరియు పరిమాణ లెక్కింపు",
    roiSubtitle: "మీ పంట మరియు రోజువారీ పరిమాణాన్ని ఎంచుకుని ఆదా అయ్యే సమయం మరియు లాభాన్ని తెలుసుకోండి.",
    selectCrop: "1. పంటను ఎంచుకోండి",
    batchQty: "2. రోజువారీ దిగుబడి (కిలోలు)",
    sunDrying: "బహిరంగ ఎండలో ఆరబెట్టడం",
    solarDrying: "ZeniTEK సోలార్ డ్రైయర్",
    daysFaster: "రోజులు వేగంగా ఆరుతుంది",
    priceIncrease: "మార్కెట్ ధర పెరుగుదల %",
    profitPerBatch: "అంచనా లాభం & పొదుపు",
    recSetup: "సూచించిన మోడల్",
    getQuoteSetup: "కొటేషన్ పొందండి",
    annualValueGain: "అంచనా వార్షిక లాభం (45 బ్యాచ్‌లు)",
    estRoi: "అంచనా వేసిన పెట్టుబడి లాభం (ROI)",
    modelsHeading: "మీ పొలానికి తగిన సోలార్ డ్రైయర్‌ను ఎంచుకోండి",
    modelsSubtitle: "10 కిలోల చిన్న డ్రైయర్ నుండి 1 టన్ను పారిశ్రామిక డ్రైయర్ వరకు.",
    reqQuote: "ధర కొటేషన్ అడగండి",
    whatCanYouDry: "ZeniTEK తో ఏమేమి ఆరబెట్టవచ్చు?",
    viewAllCrops: "అన్ని 50+ పంటల జాబితా చూడండి",
    whyChooseUs: "ZeniTEK సోలార్ ఎందుకు ఎంచుకోవాలి?",
    climateResilient: "వాతావరణ నిరోధకత",
    climateDesc: "మబ్బుల రోజుల్లో కూడా వేడిని నిలిపి ఉంచుతుంది.",
    zeroOpCost: "సున్నా నిర్వహణ ఖర్చు",
    zeroOpDesc: "100% సౌరశక్తి. కట్టెలు, కరెంట్ బిల్లుల అవసరం లేదు.",
    hygienicSetup: "100% పరిశుభ్రమైన ఆరబెట్టడం",
    hygienicDesc: "ధూళి, పురుగులు, వర్షం నుండి పూర్తి రక్షణ.",
    marketLinkage: "మార్కెటింగ్ సహాయం",
    marketDesc: "ఎండిన ఉత్పత్తులకు నేరుగా కొనుగోలుదారుల అనుసంధానం.",
    trustedBy: "1,200+ మంది రైతుల నమ్మకం",
    quickFormTitle: "వాట్సాప్‌లో తక్షణ ధరల వివరాలు & సబ్సిడీ పొందండి",
    quickFormDesc: "వివరాల కోసం 30 సెకన్ల ఫారమ్‌ను నింపండి.",
    yourName: "మీ పేరు",
    whatsappNum: "వాట్సాప్ నంబర్",
    districtCity: "రాష్ట్రం / జిల్లా",
    targetCrop: "ఆరబెట్టే పంట",
    getSubsidyQuote: "ధరల వివరాలు & సబ్సిడీ పొందండి",
    factoryLocation: "కార్యాలయాలు & కేంద్రాలు",
    callUs: "ఇంజనీరింగ్ సహాయం కోసం కాల్ చేయండి",
    emailUs: "సేల్స్ టీమ్‌కు ఇమెయిల్ చేయండి",
    chatWhatsapp: "వాట్సాప్‌లో చాట్ చేయండి",
    userCategory: "విభాగం",
    desiredCapacity: "కావలసిన సామర్థ్యం",
    additionalReqs: "అదనపు వివరాలు",
    submitProposal: "వివరాలు సమర్పించండి",
    seeMoreDetails: "మరిన్ని వివరాలు చూడండి",
    enquireSetup: "వివరాలు అడగండి",
    projectDetails: "ప్రాజెక్ట్ వివరాలు",
    moistureReduction: "తడి శాతం గురి",
    close: "మూసివేయి",
    matrixModelBadge: "సాంకేతిక వివరాల పోలిక",
    matrixModelTitle: "మోడల్ సాంకేతిక పోలిక పట్టిక",
    matrixModelSubtitle: "అన్ని ZeniTEK మోడళ్ల సామర్థ్యం, ఉష్ణోగ్రత, తయారీ రకం మరియు ప్రభుత్వ సబ్సిడీ మార్గదర్శకాలు.",
    matrixCropBadge: "పంట ఎండబెట్టడం వివరాలు",
    matrixCropTitle: "పంట తేమ శాతం పట్టిక",
    matrixCropSubtitle: "తేమ శాతం మరియు ఆరే సమయం పోలిక: ZeniTEK సోలార్ డ్రైయర్ వర్సెస్ బహిరంగ ఎండ.",
    searchPlaceholder: "పంట లేదా లాభాలను వెతకండి...",
    dryerModel: "డ్రైయర్ మోడల్",
    descriptionReqs: "వివరాలు / అదనపు అవసరాలు",
    getPricingSubsidyQuote: "ధరల వివరాలు & సబ్సిడీ పొందండి",

    // About Us Page
    aboutBadge: "ZeniTEK సోలార్ గురించి",
    aboutTitle1: "రైతుల సాధికారత.",
    aboutTitle2: "పంట నష్టానికి సంపూర్ణ అడ్డుకట్ట.",
    aboutSubtitle: "కోయంబత్తూర్ ప్రధాన కేంద్రంగా ZeniTEK అత్యుత్తమ సోలార్ డ్రైయర్లను తయారు చేస్తోంది.",
    aboutHub: "కోయంబత్తూర్ తయారీ కేంద్రం",
    aboutInnovation: "2 దశాబ్దాలకు పైగా సోలార్ థర్మల్ అనుభవం",
    aboutP1: "వ్యవసాయ వ్యర్థాలను నివారించడం మరియు సౌర సాంకేతికతను రైతులకు అందించడమే మా ధ్యేయం.",
    aboutP2: "మా 25,000 చదరపు అడుగుల ఫ్యాక్టరీలో నాణ్యమైన డ్రైయర్లు తయారవుతాయి.",
    aboutF1: "✓ 25,000+ చ.అడుగుల ఫ్యాక్టరీ",
    aboutF2: "✓ సొంత టెస్టింగ్ ల్యాబ్",
    aboutPillarsTitle: "మా 3 సాంకేతిక స్తంభాలు",
    aboutPillarsSubtitle: "మేము తయారుచేసే ప్రతీ డ్రైయర్‌లో అద్భుతమైన ఇంజనీరింగ్ నైపుణ్యం.",
    pillar1Title: "పరిశోధన & ఆవిష్కరణ",
    pillar1Desc: "ఉష్ణ నిల్వ మరియు UV పాలిహౌస్ కాంతి సాంకేతికత.",
    pillar2Title: "నాణ్యత ప్రమాణాలు",
    pillar2Desc: "ISO 9001:2015 మరియు CE ప్రమాణాలకు అనుగుణంగా తయారీ.",
    pillar3Title: "కార్బన్ ఉద్గారాల తగ్గింపు",
    pillar3Desc: "సంవత్సరానికి 15,000 టన్నుల CO₂ ఉద్గారాలను తగ్గిస్తున్నాం.",
    impact1: "లబ్ధి పొందిన రైతులు & FPOలు",
    impact2: "కాపాడిన పంటలు",
    impact3: "రైతు ఆదాయం పెంపు",
    impact4: "సబ్సిడీ సహాయం",
    govtBadgesTitle: "ప్రభుత్వ గుర్తింపులు",
    mnreApproved: "MNRE గుర్తింపు పొందిన సంస్థ",
    isoSystem: "ISO 9001:2015 సిస్టమ్",
    ceMarked: "CE గుర్తింపు పొందిన పరికరాలు",
    consultEngineers: "మా ఇంజనీర్లను సంప్రదించండి",

    // Applications Page
    appMatrixBadge: "వివిధ పంటల వినియోగ పట్టిక",
    appMatrixTitle1: "50 కి పైగా వ్యవసాయ ఉత్పత్తులను",
    appMatrixTitle2: "ఎండబెట్టే సోలార్ డ్రైయర్లు",
    appMatrixSubtitle: "పోషకాలు, రంగు మరియు సువాసన చెడిపోకుండా ఉండే ఎండబెట్టే పద్ధతులు.",
    tabAgri: "🌾 వ్యవసాయ ఉత్పత్తులు (కొబ్బరి, మురింగ, మసాలాలు)",
    tabMarine: "🐟 సముద్ర ఉత్పత్తులు (ఎండిన చేపలు, రొయ్యలు)",
    tabIndustrial: "🏭 పారిశ్రామిక ఉత్పత్తులు (రబ్బరు, కలప)",
    thTargetProduce: "ఉత్పత్తి",
    thFreshMoisture: "తొలి తేమ %",
    thDriedMoisture: "చివరి తేమ %",
    thSolarTime: "ZeniTEK సమయం",
    thSunTime: "సాధారణ ఎండ సమయం",
    thProfitBenefit: "ముఖ్య లాభం",
    tailoredSolutions: "మీ అవసరాలకు తగిన పరిష్కారాలు",
    personaFpoTitle: "FPOలు మరియు రైతు సంఘాలకు",
    personaFpoDesc: "రోజుకు 500 కిలోలకు పైగా ఆరబెట్టే పెద్ద డ్రైయర్లు.",
    personaFpoBtn: "FPO వివరాలు పొందండి →",
    personaExpTitle: "ఎగుమతిదారులకు",
    personaExpDesc: "అంతర్జాతీయ ప్రమాణాలతో ఆటోమేటిక్ డ్రైయర్లు.",
    personaExpBtn: "ఎగుమతి వివరాలు పొందండి →",
    personaFarmerTitle: "చిన్న రైతులకు",
    personaFarmerDesc: "40% ప్రభుత్వ సబ్సిడీతో లభించే చిన్న డ్రైయర్లు.",
    personaFarmerBtn: "రైతు వివరాలు పొందండి →",

    // Contact Us Page
    contactBadge: "నేరుగా ఫ్యాక్టరీని సంప్రదించండి",
    contactTitle1: "మీ పొలానికి తగిన",
    contactTitle2: "సోలార్ డ్రైయర్ నిర్మిద్దాం.",
    contactSubtitle: "సబ్సిడీ మరియు ధరల వివరాల కోసం మా బృందాన్ని సంప్రదించండి.",
    regOfficeLabel: "రిజిస్టర్డ్ కార్యాలయం (ప్రధాన చిరునామా)",
    regOfficeAddress: "4/501, Aitreya garden, Athappam palayam, Vallipurathanpalayam (PO), Erode (Dt), Tamil Nadu, PIN: 638 112",
    opOfficeLabel: "కార్యాచరణ చిరునామా",
    opOfficeAddress: "Zenitek Incubation center, SSM College of Engineering, NH-544, Valayakaranur, Komarapalayam, Namakkal Dt. - 638 183",
    gstinLabel: "GSTIN",
    gstinNumber: "33AACFZ8530G1Z5",
    primaryPhone: "+91-8903852623",
    primaryEmail: "zenitek2k@gmail.com",
    factoryAddressLabel: "రిజిస్టర్డ్ కార్యాలయం (ప్రధాన చిరునామా)",
    factoryAddressText: "4/501, Aitreya garden, Athappam palayam, Vallipurathanpalayam (PO), Erode (Dt), Tamil Nadu, PIN: 638 112",
    operationAddressLabel: "కార్యాచరణ చిరునామా",
    operationAddressText: "Zenitek Incubation center, SSM College of Engineering, NH-544, Valayakaranur, Komarapalayam, Namakkal Dt. - 638 183",
    workingHours: "సోమ - శని: 9:00 AM - 7:00 PM",
    preQualTitle: "ధరల వివరాల ఫారమ్",
    support1: "ఉచిత సబ్సిడీ అర్హత తనిఖీ",
    support2: "తేమ శాతం విశ్లేషణ సహాయం",
    support3: "100% ఫీల్డ్ ఇన్‌స్టాలేషన్ మరియు శిక్షణ",
    csrBadge: "CSR & NGO భాగస్వామ్యం",
    csrTitle: "గ్రామీణ అభివృద్ధి ప్రాజెక్ట్‌ల కోసం మాతో చేరండి",
    csrDesc: "మహిళా సంఘాలకు డ్రైయర్లు అందించడానికి CSR నిధులతో పనిచేస్తున్నాం.",
    csrBtn: "CSR వివరాలు అడగండి",

    // Farmer Stories Page
    storiesBadge: "రైతుల విజయగాథలు",
    storiesTitle1: "నిజమైన కథలు. నిజమైన ఎదుగుదల.",
    storiesTitle2: "పంట నష్టం లేని వ్యవసాయం.",
    storiesSubtitle: "ZeniTEK తో లాభాలు పొందిన రైతుల అనుభవాలు.",
    impactFamilies: "లబ్ధి పొందిన రైతు కుటుంబాలు",
    impactValue: "రైతులకు సమకూరిన అదనపు లాభం",
    impactCrops: "కాపాడిన పంటలు",
    impactCleanEnergy: "100% సౌరశక్తి",
    videoReviewsTitle: "రైతుల వీడియో అనుభవాలు",
    videoReviewsSub: "తమిళనాడు, కేరళ, మహారాష్ట్ర రైతుల వీడియో ఇంటర్వ్యూలు.",
    caseStudiesTitle: "కేస్ స్టడీస్",
    pollachiCollective: "పొల్లాచి కొబ్బరి రైతుల సంఘం",
    pollachiTitle: "50 మంది రైతులు వర్షం నష్టాన్ని నివారించి ఆదాయాన్ని 28% ఎలా పెంచుకున్నారు?",
    probTitle: "సమస్య",
    probDesc: "అకాల వర్షాల వల్ల 30% కొబ్బరి బూజు పట్టి నశించేది.",
    solTitle: "పరిష్కారం",
    solDesc: "50% సబ్సిడీతో 500 కిలోల సోలార్ డ్రైయర్ ఏర్పాటు చేశారు.",
    resTitle: "ఫలితం",
    resDesc: "2.5 రోజుల్లో 100% మొదటి రకం తెల్ల కొబ్బరి ఎండింది. కిలోకు ₹18 అదనపు లాభం.",
    commitmentTitle: "మా 360° మద్దతు హామీ",
    comm1Title: "పూర్తి సబ్సిడీ సహాయం",
    comm1Desc: "బ్యాంకు రుణాలు మరియు సబ్సిడీ దరఖాస్తులను మేమే నిర్వహిస్తాం.",
    comm2Title: "ఫీల్డ్ ఇన్‌స్టాలేషన్ & శిక్షణ",
    comm2Desc: "మా ఇంజనీర్లు మీ పొలంలో ఏర్పాటు చేసి శిక్షణ ఇస్తారు.",
    comm3Title: "మార్కెట్ అనుసంధానం",
    comm3Desc: "ఉత్పత్తులకు నేరుగా కొనుగోలుదారులతో అనుసంధానం చేస్తాం.",
    startProsperityBtn: "ఈరోజే మీ విజయ ప్రయాణాన్ని ప్రారంభించండి",

    // Gallery Page
    galleryBadge: "గ్యాలరీ మరియు ప్రాజెక్ట్‌లు",
    galleryTitle1: "ZeniTEK సోలార్ డ్రైయర్లు",
    galleryTitle2: "మరియు ఉత్పత్తుల చిత్రాలు",
    gallerySubtitle: "వివిధ రాష్ట్రాల్లో ఏర్పాటు చేసిన డ్రైయర్లు మరియు ఎండిన ఉత్పత్తుల ఫోటోలు.",
    catAll: "అన్ని ఫోటోలు",
    catInstallations: "ఏర్పాటు చేసిన ప్రదేశాలు",
    catProduce: "ఎండిన ఉత్పత్తుల నాణ్యత",
    catModels: "డ్రైయర్ మోడల్స్",
    catFactory: "ఫ్యాక్టరీ",
    viewEnlarged: "పెద్దదిగా చూడండి",
    clickFullSpec: "పూర్తి వివరాల కోసం క్లిక్ చేయండి",
    customDryerBadge: "మీ సోలార్ డ్రైయర్ పొందండి",
    customDryerTitle: "మీకు కూడా ఇలాంటి సోలార్ డ్రైయర్ కావాలా?",
    customDryerDesc: "40%-60% ప్రభుత్వ సబ్సిడీ సహాయంతో డ్రైయర్లు ఏర్పాటు చేస్తాం.",
    locationLabel: "ప్రదేశం:",
    requestQuoteForModel: "ఈ మోడల్ వివరాలు అడగండి",

    // Solar Dryers Page
    catalogueBadge: "సోలార్ డ్రైయర్ క్యాటలాగ్",
    catalogueTitle1: "100% సౌరశక్తి డ్రైయర్లు.",
    catalogueTitle2: "5 రెట్లు వేగం. కరెంట్ బిల్లు లేదు.",
    catalogueSubtitle: "వివిధ రకాల డ్రైయర్ మోడళ్లను పరిశీలించండి. వివరాల కోసం క్లిక్ చేయండి.",
    browseCapacity: "సామర్థ్యం ఆధారంగా",
    browseCrop: "పంట రకం ఆధారంగా",
    clickSpecs: "పూర్తి వివరాలకు క్లిక్ చేయండి",
    targetAudienceLabel: "ఎవరికి ఉపయుక్తం",
    buildMaterialLabel: "తయారీ మెటీరియల్",
    tempRangeLabel: "ఉష్ణోగ్రత పరిమితి",
    subsidyEligibilityLabel: "సబ్సిడీ అర్హత",
    viewSpecsPhotos: "వివరాలు & ఫోటోలు చూడండి",
    checkSubsidyPricing: "ధరలు & సబ్సిడీ తెలుసుకోండి",
    thSpecParam: "సాంకేతిక వివరాలు",
    thPortable: "చిన్న డ్రైయర్",
    thPolyhouse: "పాలిహౌస్ డ్రైయర్",
    thIndustrial: "ఇండస్ట్రియల్ డ్రైయర్",
    stateAssistance: "రాష్ట్ర ప్రభుత్వ సబ్సిడీ సహాయం",
    claimSubsidyTitle: "60% వరకు ప్రభుత్వ సబ్సిడీ పొందండి",
    claimSubsidyDesc: "NABARD మరియు ప్రభుత్వ సబ్సిడీ ప్రక్రియలో సంపూర్ణ సహాయం అందించబడుతుంది.",
    checkSubsidyBtn: "సబ్సిడీ అర్హత చూడండి",

    // Map Page & Component
    mapShowcaseBadge: "మ్యాప్ సమాచారం",
    mapTitle1: "నడుస్తున్న సోలార్ డ్రైయర్లు",
    mapTitle2: "దక్షిణ భారతదేశం అంతటా",
    mapSubtitle: "మ్యాప్‌లో మా సోలార్ డ్రైయర్లు ఉన్న ప్రదేశాలు మరియు వివరాలు చూడండి.",
    filterStateLabel: "రాష్ట్రం ఎంచుకోండి:",
    interactiveMapMapTab: "మ్యాప్",
    projectListTab: "జాబితా",
    visitTitle: "సమీపంలోని డ్రైయర్‌ను నేరుగా చూడాలనుకుంటున్నారా?",
    visitDesc: "రైతుల కోసం ప్రత్యక్ష సందర్శన ఏర్పాటు చేస్తాం.",
    bookVisitBtn: "సందర్శన బుక్ చేయండి",

    // Footer
    footerAbout: "అధిక సామర్థ్యం కలిగిన సోలార్ డ్రైయర్ల తయారీలో భారతదేశంలో ప్రముఖ సంస్థ.",
    footerDryerModels: "సోలార్ డ్రైయర్ మోడల్స్",
    footerDownloads: "డౌన్‌లోడ్‌లు",
    footerCatalog: "ప్రొడక్ట్ క్యాటలాగ్ (PDF)",
    footerSubsidyGuide: "సబ్సిడీ గైడ్ 2026",
    footerLabReport: "కొబ్బరి టెస్ట్ రిపోర్ట్",
    footerCoimbatoreFactory: "కార్యాలయాలు & సంప్రదించండి",
    footerOffices: "కార్యాలయాలు & సంప్రదించండి",
    footerRights: "అన్ని హక్కులు రక్షించబడ్డాయి.",
    footerPrivacy: "గోప్యతా విధానం",
    footerTerms: "నిబంధనలు",

    // Crops
    cropCopra: "కొబ్బరి / కొప్రా",
    cropMoringa: "మురింగ / ఆకులు / టీ",
    cropSpices: "మిర్చి / మసాలాలు",
    cropFruits: "పండ్లు & కూరగాయలు",
    cropFish: "చేపలు / రొయ్యలు",
    cropOther: "ఇతర పంటలు",

    // Models
    modelPortable: "చిన్న సోలార్ డ్రైయర్",
    modelPolyhouse: "పాలిహౌస్ సోలార్ డ్రైయర్",
    modelIndustrial: "ఇండస్ట్రియల్ సోలార్ డ్రైయర్"
  },

  kn: {
    announcement: "MNRE അംഗീകൃത & ISO 9001:2015 ಪ್ರಮಾಣೀಕೃತ | ಕಾರ್ಖಾನೆ: ಕೊಯಮತ್ತೂರು",
    subsidyBadge: "40% - 60% ಸರ್ಕಾರಿ ಸಬ್ಸಿಡಿ ಲಭ್ಯ",
    navHome: "ಮುಖಪುಟ",
    navAbout: "ನಮ್ಮ ಬಗ್ಗೆ",
    navDryers: "ಸೋಲಾರ್ ಡ್ರೈಯರ್‌ಗಳು",
    navApplications: "ಅನ್ವಯಗಳು",
    navGallery: "ಗ್ಯಾಲರಿ",
    navStories: "ರೈತರ ಕಥೆಗಳು",
    navMap: "ನಕ್ಷೆ",
    navContact: "ಸಂಪರ್ಕಿಸಿ",
    getQuote: "ಉಚಿತ ಧಾರಣೆ ಪಡೆಯಿರಿ",
    heroBadge: "ಮುಂದಿನ ಪೀಳಿಗೆಯ ಸೋಲಾರ್ ಥರ್ಮಲ್ ಆಹಾರ ಸಂರಕ್ಷಣಾ ತಂತ್ರಜ್ಞಾನ",
    heroTitle1: "ಕೊಯ್ಲೋತ್ತರ ನಷ್ಟ ತಡೆಯಿರಿ.",
    heroTitle2: "ಕೃಷಿ ಲಾಭವನ್ನು ಹೆಚ್ಚಿಸಿ.",
    heroSubtitle: "ವಿದ್ಯುತ್ ಬಿಲ್ ಇಲ್ಲದೆ ಬಣ್ಣ, ಸುವಾಸನೆ ಮತ್ತು ಪೋಷಕಾಂಶಗಳನ್ನು ಕಾಯ್ದುಕೊಳ್ಳುವ 100% ಸೌರಶಕ್ತಿ ಡ್ರೈಯರ್.",
    calcSavings: "ಬಳಕೆಯ ಉಳಿತಾಯ ಲೆಕ್ಕಹಾಕಿ",
    exploreModels: "ಡ್ರೈಯರ್ ಮಾದರಿಗಳನ್ನು ನೋಡಿ",
    dryersInstalled: "ಅಳವಡಿಸಲಾದ ಡ್ರೈಯರ್‌ಗಳು",
    foodSaved: "ವರ್ಷಕ್ಕೆ ಉಳಿಸಿದ ಬೆಳೆ",
    subsidyHelp: "ಸರ್ಕಾರಿ ಸಬ್ಸಿಡಿ ನೆರವು",
    mnreBadge: "MNRE ಅನುಮೋದಿತ ಮಾದರಿ",
    isoBadge: "ISO 9001:2015 ಗುಣಮಟ್ಟದ ಪ್ರಮಾಣಪತ್ರ",
    subsidyBadge2: "100% ರಾಜ್ಯ ಸಬ್ಸಿಡಿ ಅರ್ಹತೆ",
    roiTitle: "ಲಾಭ ಮತ್ತು ಸಾಮರ್ಥ್ಯ ಲೆಕ್ಕಾಚಾರ",
    roiSubtitle: "ನಿಮ್ಮ ಬೆಳೆ ಮತ್ತು ಪ್ರಮಾಣ ಆಯ್ಕೆಮಾಡಿ ಒಣಗಿಸುವ ಸಮಯ ಹಾಗೂ ಲಾಭ ತಿಳಿಯಿರಿ.",
    selectCrop: "1. ಬೆಳೆ ಆಯ್ಕೆಮಾಡಿ",
    batchQty: "2. ಬ್ಯಾಚ್ ಇಳುವರಿ ಪ್ರಮಾಣ (ಕೆಜಿ)",
    sunDrying: "ಬಯಲು ಬಿಸಿಲಿನಲ್ಲಿ ಒಣಗಿಸುವುದು",
    solarDrying: "ZeniTEK ಸೋಲಾರ್ ಡ್ರೈಯರ್",
    daysFaster: "ದಿನಗಳ ವೇಗದ ಒಣಗಿಸುವಿಕೆ",
    priceIncrease: "ಮಾರುಕಟ್ಟೆ ಬೆಲೆ ಏರಿಕೆ %",
    profitPerBatch: "ಅಂದಾಜು ಲಾಭ ಮತ್ತು ಉಳಿತಾಯ",
    recSetup: "ಶಿಫಾರಸು ಮಾಡಿದ ಮಾದರಿ",
    getQuoteSetup: "ಧಾರಣೆ ಪಡೆಯಿರಿ",
    annualValueGain: "ಅಂದಾಜು ವಾರ್ಷಿಕ ಹೆಚ್ಚುವರಿ ಲಾಭ (45 ಬ್ಯಾಚ್‌ಗಳು)",
    estRoi: "ಅಂದಾಜು ಹೂಡಿಕೆ ಲಾಭ (ROI)",
    modelsHeading: "ನಿಮ್ಮ ಜಮೀನಿಗೆ ಸೂಕ್ತವಾದ ಸೋಲಾರ್ ಡ್ರೈಯರ್ ಆಯ್ಕೆಮಾಡಿ",
    modelsSubtitle: "10 ಕೆಜಿ ಗೃಹಬಳಕೆಯ ಡ್ರೈಯರ್‌ನಿಂದ 1 ಟನ್ ಕೈಗಾರಿಕಾ ಡ್ರೈಯರ್‌ವರೆಗೆ.",
    reqQuote: "ಧಾರಣೆ ವಿನಂತಿಸಿ",
    whatCanYouDry: "ZeniTEK ಮೂಲಕ ಏನನ್ನೆಲ್ಲಾ ಒಣಗಿಸಬಹುದು?",
    viewAllCrops: "ಎಲ್ಲಾ 50+ ಬೆಳೆಗಳ ಪಟ್ಟಿ ನೋಡಿ",
    whyChooseUs: "ZeniTEK ಸೋಲಾರ್ ಏಕೆ ಆಯ್ಕೆ ಮಾಡಬೇಕು?",
    climateResilient: "ಹವಾಮಾನ ನಿರೋಧಕ",
    climateDesc: "ಮೋಡ ಕವಿದ ದಿನಗಳಲ್ಲೂ ಶಾಖವನ್ನು ಕಾಯ್ದುಕೊಳ್ಳುತ್ತದೆ.",
    zeroOpCost: "ಶೂನ್ಯ ನಿರ್ವಹಣಾ ವೆಚ್ಚ",
    zeroOpDesc: "100% ಸೌರಶಕ್ತಿ. ಸೌದೆ, ವಿದ್ಯುತ್ ಬಿಲ್ ಅಗತ್ಯವಿಲ್ಲ.",
    hygienicSetup: "100% ನೈರ್ಮಲ್ಯದ ಒಣಗಿಸುವಿಕೆ",
    hygienicDesc: "ಧೂಳು, ಕೀಟಗಳು ಮತ್ತು ಮಳೆಯಿಂದ ಸಂಪೂರ್ಣ ರಕ್ಷಣೆ.",
    marketLinkage: "ಮಾರುಕಟ್ಟೆ ನೆರವು",
    marketDesc: "ಒಣಗಿಸಿದ ಉತ್ಪನ್ನಗಳಿಗೆ ನೇರ ಮಾರುಕಟ್ಟೆ ಸಂಪರ್ಕ.",
    trustedBy: "1,200+ ರೈತರ ನಂಬಿಕೆ",
    quickFormTitle: "ವಾಟ್ಸಾಪ್‌ನಲ್ಲಿ ತಕ್ಷಣದ ಬೆಲೆ ಮತ್ತು ಸಬ್ಸಿಡಿ ವಿವರ ಪಡೆಯಿರಿ",
    quickFormDesc: "ಮಾಹಿತಿಗಾಗಿ 30 ಸೆಕೆಂಡ್‌ಗಳ ಅರ್ಜಿ ಭರ್ತಿ ಮಾಡಿ.",
    yourName: "ನಿಮ್ಮ ಹೆಸರು",
    whatsappNum: "ವಾಟ್ಸಾಪ್ ಸಂಖ್ಯೆ",
    districtCity: "ರಾಜ್ಯ / ಜಿಲ್ಲೆ",
    targetCrop: "ಒಣಗಿಸುವ ಬೆಳೆ",
    getSubsidyQuote: "ಬೆಲೆ ಮತ್ತು ಸಬ್ಸಿಡಿ ಧಾರಣೆ ಪಡೆಯಿರಿ",
    factoryLocation: "ಕಚೇರಿಗಳು & ಕಾರ್ಯಾಚರಣೆಗಳು",
    callUs: "ಇಂಜಿನಿಯರಿಂಗ್ ನೆರವಿಗಾಗಿ ಕರೆ ಮಾಡಿ",
    emailUs: "ಸೇಲ್ಸ್ ತಂಡಕ್ಕೆ ಇಮೇಲ್ ಮಾಡಿ",
    chatWhatsapp: "ವಾಟ್ಸಾಪ್‌ನಲ್ಲಿ ತಕ್ಷಣ ಚಾಟ್ ಮಾಡಿ",
    userCategory: "ವರ್ಗ",
    desiredCapacity: "ಅಗತ್ಯವಿರುವ ಸಾಮರ್ಥ್ಯ",
    additionalReqs: "ಹೆಚ್ಚಿನ ವಿವರಗಳು",
    submitProposal: "ಅರ್ಜಿ ಸಲ್ಲಿಸಿ",
    seeMoreDetails: "ಹೆಚ್ಚಿನ ವಿವರಗಳನ್ನು ನೋಡಿ",
    enquireSetup: "ಧಾರಣೆ ಕೇಳಿ",
    projectDetails: "ಯೋಜನೆಯ ವಿವರಗಳು",
    moistureReduction: "ತೇವಾಂಶದ ಮಟ್ಟ",
    close: "ಮುಚ್ಚಿ",
    matrixModelBadge: "ತಾಂತ್ರಿಕ ವಿವರಣೆ ಹೋಲಿಕೆ",
    matrixModelTitle: "ಮಾದರಿ ತಾಂತ್ರಿಕ ಹೋಲಿಕೆ ಕೋಷ್ಟಕ",
    matrixModelSubtitle: "ಎಲ್ಲಾ ZeniTEK ಮಾದರಿಗಳ ಸಾಮರ್ಥ್ಯ, ತಾಪಮಾನ, ನಿರ್ಮಾಣ ಗುಣಮಟ್ಟ ಮತ್ತು ಸರ್ಕಾರಿ ಸಬ್ಸಿಡಿ ಮಾರ್ಗದರ್ಶಿಗಳು.",
    matrixCropBadge: "ಬೆಳೆ ಒಣಗಿಸುವ ವಿವರಗಳು",
    matrixCropTitle: "ಬೆಳೆ ತೇವಾಂಶ ಮಟ್ಟದ ಕೋಷ್ಟಕ",
    matrixCropSubtitle: "ತೇವಾಂಶ ಮತ್ತು ಒಣಗಿಸುವ ಸಮಯದ ಹೋಲಿಕೆ: ZeniTEK ಸೋಲಾರ್ ಡ್ರೈಯರ್ ವಿರುದ್ಧ ಬಯಲು ಬಿಸಿಲು.",
    searchPlaceholder: "ಬೆಳೆ ಅಥವಾ ಲಾಭ ಹುಡುಕಿ...",
    dryerModel: "ಡ್ರೈಯರ್ ಮಾದರಿ",
    descriptionReqs: "ವಿವರಣೆ / ಹೆಚ್ಚುವರಿ ಅಗತ್ಯಗಳು",
    getPricingSubsidyQuote: "ಬೆಲೆ ಮತ್ತು ಸಬ್ಸಿಡಿ ಧಾರಣೆ ಪಡೆಯಿರಿ",

    // About Us Page
    aboutBadge: "ZeniTEK ಸೋಲಾರ್ ಬಗ್ಗೆ",
    aboutTitle1: "ರೈತರ ಸಬಲೀಕರಣ.",
    aboutTitle2: "ಕೊಯ್ಲೋತ್ತರ ನಷ್ಟಕ್ಕೆ ಪೂರ್ಣ ತಡೆ.",
    aboutSubtitle: "ಕೊಯಮತ್ತೂರಿನಲ್ಲಿ ಪ್ರಧಾನ ಕಚೇರಿ ಹೊಂದಿರುವ ZeniTEK ಸೋಲಾರ್ ಡ್ರೈಯರ್‌ಗಳನ್ನು ತಯಾರಿಸುತ್ತದೆ.",
    aboutHub: "ಕೊಯಮತ್ತೂರು ತಯಾರಿಕಾ ಕೇಂದ್ರ",
    aboutInnovation: "2 ದಶಕಕ್ಕೂ ಹೆಚ್ಚು ಸೋಲಾರ್ ಥರ್ಮಲ್ ಅನುಭವ",
    aboutP1: "ಕೃಷಿ ತ್ಯಾಜ್ಯವನ್ನು ತಡೆದು ಸೌರ ತಂತ್ರಜ್ಞಾನವನ್ನು ರೈತರಿಗೆ ತಲುಪಿಸುವುದೇ ನಮ್ಮ ಗುರಿ.",
    aboutP2: "ನಮ್ಮ 25,000 ಚದರ ಅಡಿ ಕಾರ್ಖಾನೆಯಲ್ಲಿ ಗುಣಮಟ್ಟದ ಡ್ರೈಯರ್‌ಗಳನ್ನು ತಯಾರಿಸಲಾಗುತ್ತದೆ.",
    aboutF1: "✓ 25,000+ ಚದರ ಅಡಿ ಕಾರ್ಖಾನೆ",
    aboutF2: "✓ ಸ್ವಂತ ಪರೀಕ್ಷಾ ಪ್ರಯೋಗಾಲಯ",
    aboutPillarsTitle: "ನಮ್ಮ 3 ತಾಂತ್ರಿಕ ಸ್ತಂಭಗಳು",
    aboutPillarsSubtitle: "ನಾವು ತಯಾರಿಸುವ ಪ್ರತಿಯೊಂದು ಡ್ರೈಯರ್‌ನಲ್ಲೂ ತಾಂತ್ರಿಕ ಶ್ರೇಷ್ಠತೆ.",
    pillar1Title: "ಸಂಶೋಧನೆ ಮತ್ತು ನಾವೀನ್ಯತೆ",
    pillar1Desc: "ಶಾಖ ಸಂಗ್ರಹಣೆ ಮತ್ತು UV ಪಾಲಿಹೌಸ್ ಬೆಳಕಿನ ತಂತ್ರಜ್ಞಾನ.",
    pillar2Title: "ಗುಣಮಟ್ಟದ ಮಾನದಂಡಗಳು",
    pillar2Desc: "ISO 9001:2015 ಮತ್ತು CE ಮಾನದಂಡಗಳ ಪ್ರಕಾರ ತಯಾರಿಕೆ.",
    pillar3Title: "ಕಾರ್ಬನ್ ಹೊರಸೂಸುವಿಕೆ ಕಡಿತ",
    pillar3Desc: "ವರ್ಷಕ್ಕೆ 15,000 ಟನ್‌ಗಿಂತ ಹೆಚ್ಚು CO₂ ಹೊರಸೂಸುವಿಕೆಯನ್ನು ಕಡಿಮೆಗೊಳಿಸುತ್ತಿದ್ದೇವೆ.",
    impact1: "ಫಲಾನುಭವಿ ರೈತರು & FPOಗಳು",
    impact2: "ಉಳಿಸಿದ ಬೆಳೆ",
    impact3: "ರೈತರ ಆದಾಯ ಹೆಚ್ಚಳ",
    impact4: "ಸಬ್ಸಿಡಿ ನೆರವು",
    govtBadgesTitle: "ಸರ್ಕಾರಿ ಸಮ್ಮತಿಗಳು",
    mnreApproved: "MNRE ಅನುಮೋದಿತ ತಯಾರಕರು",
    isoSystem: "ISO 9001:2015 ಸಿಸ್ಟಮ್",
    ceMarked: "CE ಪ್ರಮಾಣೀಕೃತ ಬಿಡಿಭಾಗಗಳು",
    consultEngineers: "ನಮ್ಮ ಇಂಜಿನಿಯರ್‌ಗಳನ್ನು ಸಂಪರ್ಕಿಸಿ",

    // Applications Page
    appMatrixBadge: "ವಿವಿಧ ಬೆಳೆ ಬಳಕೆಯ ಕೋಷ್ಟಕ",
    appMatrixTitle1: "50 ಕ್ಕೂ ಹೆಚ್ಚು ಕೃಷಿ ಉತ್ಪನ್ನಗಳನ್ನು",
    appMatrixTitle2: "ಒಣಗಿಸುವ ಸೋಲಾರ್ ಡ್ರೈಯರ್‌ಗಳು",
    appMatrixSubtitle: "ಪೋಷಕಾಂಶಗಳು ಮತ್ತು ಬಣ್ಣವನ್ನು ಕಾಯ್ದುಕೊಳ್ಳುವ ಅತ್ಯುತ್ತಮ ಒಣಗಿಸುವಿಕೆ.",
    tabAgri: "🌾 ಕೃಷಿ & ಆಹಾರ (ಕೊಬ್ಬರಿ, ನುಗ್ಗೆ, ಸಾಂಬಾರು)",
    tabMarine: "🐟 ಸಮುದ್ರ ಉತ್ಪನ್ನಗಳು (ಒಣಮೀನು, ಸಿಗಡಿ)",
    tabIndustrial: "🏭 ಕೈಗಾರಿಕಾ ಉತ್ಪನ್ನಗಳು (ರಬ್ಬರ್, ಮರ)",
    thTargetProduce: "ಉತ್ಪನ್ನ",
    thFreshMoisture: "ಆರಂಭಿಕ ತೇವಾಂಶ %",
    thDriedMoisture: "ಅಂತಿಮ ತೇವಾಂಶ %",
    thSolarTime: "ZeniTEK ಸಮಯ",
    thSunTime: "ಸಾಮಾನ್ಯ ಸಮಯ",
    thProfitBenefit: "ಮುಖ್ಯ ಲಾಭ",
    tailoredSolutions: "ನಿಮ್ಮ ಅಗತ್ಯಕ್ಕೆ ಸೂಕ್ತವಾದ ಪರಿಹಾರಗಳು",
    personaFpoTitle: "FPO ಮತ್ತು ಸಂಘಗಳಿಗೆ",
    personaFpoDesc: "ದಿನಕ್ಕೆ 500 ಕೆಜಿಗಿಂತ ಹೆಚ್ಚು ಒಣಗಿಸುವ ಸಾಮರ್ಥ್ಯದ ಡ್ರೈಯರ್‌ಗಳು.",
    personaFpoBtn: "FPO ಆಫರ್ ಪಡೆಯಿರಿ →",
    personaExpTitle: "ರಫ್ತುದಾರರಿಗೆ",
    personaExpDesc: "ಅಂತರರಾಷ್ಟ್ರೀಯ ಮಾನದಂಡದ ಆಟೋಮ್ಯಾಟಿಕ್ ಡ್ರೈಯರ್‌ಗಳು.",
    personaExpBtn: "ರಫ್ತು ಆಫರ್ ಪಡೆಯಿರಿ →",
    personaFarmerTitle: "ಸಣ್ಣ ರೈತರಿಗೆ",
    personaFarmerDesc: "40% ಸರ್ಕಾರಿ ಸಬ್ಸಿಡಿಯೊಂದಿಗೆ ಲಭ್ಯವಿರುವ ಸಣ್ಣ ಡ್ರೈಯರ್‌ಗಳು.",
    personaFarmerBtn: "ರೈತರ ಆಫರ್ ಪಡೆಯಿರಿ →",

    // Contact Us Page
    contactBadge: "ನೇರ ಕಾರ್ಖಾನೆ ಸಂಪರ್ಕ",
    contactTitle1: "ನಿಮ್ಮ ಜಮೀನಿಗೆ ಸೂಕ್ತವಾದ",
    contactTitle2: "ಸೋಲಾರ್ ಡ್ರೈಯರ್ ನಿರ್ಮಿಸೋಣ.",
    contactSubtitle: "ಸಬ್ಸಿಡಿ ಮತ್ತು ಬೆಲೆ ವಿವರಗಳಿಗಾಗಿ ನಮ್ಮ ತಂಡವನ್ನು ಸಂಪರ್ಕಿಸಿ.",
    regOfficeLabel: "ನೋಂದಾಯಿತ ಕಚೇರಿ (ಮುಖ್ಯ ವಿಳಾಸ)",
    regOfficeAddress: "4/501, Aitreya garden, Athappam palayam, Vallipurathanpalayam (PO), Erode (Dt), Tamil Nadu, PIN: 638 112",
    opOfficeLabel: "ಕಾರ್ಯಾಚರಣೆ ವಿಳಾಸ",
    opOfficeAddress: "Zenitek Incubation center, SSM College of Engineering, NH-544, Valayakaranur, Komarapalayam, Namakkal Dt. - 638 183",
    gstinLabel: "GSTIN",
    gstinNumber: "33AACFZ8530G1Z5",
    primaryPhone: "+91-8903852623",
    primaryEmail: "zenitek2k@gmail.com",
    factoryAddressLabel: "ನೋಂದಾಯಿತ ಕಚೇರಿ (ಮುಖ್ಯ ವಿಳಾಸ)",
    factoryAddressText: "4/501, Aitreya garden, Athappam palayam, Vallipurathanpalayam (PO), Erode (Dt), Tamil Nadu, PIN: 638 112",
    operationAddressLabel: "ಕಾರ್ಯಾಚರಣೆ ವಿಳಾಸ",
    operationAddressText: "Zenitek Incubation center, SSM College of Engineering, NH-544, Valayakaranur, Komarapalayam, Namakkal Dt. - 638 183",
    workingHours: "ಸೋಮ - ಶನಿ: 9:00 AM - 7:00 PM",
    preQualTitle: "ಬೆಲೆ ವಿವರ ಪಡೆಯುವ ಅರ್ಜಿ",
    support1: "ಉಚಿತ ಸಬ್ಸಿಡಿ ಅರ್ಹತಾ ತಪಾಸಣೆ",
    support2: "ತೇವಾಂಶ ವಿಶ್ಲೇಷಣೆ ನೆರವು",
    support3: "100% ಅನುಸ್ಥಾಪನೆ ಮತ್ತು ತರಬೇತಿ",
    csrBadge: "CSR & NGO ಸಹಭಾಗಿತ್ವ",
    csrTitle: "ಗ್ರಾಮೀಣ ಅಭಿವೃದ್ಧಿ ಯೋಜನೆಗಳಿಗಾಗಿ ನಮ್ಮೊಂದಿಗೆ ಕೈಜೋಡಿಸಿ",
    csrDesc: "ಮಹಿಳಾ ಸಂಘಗಳಿಗೆ ಡ್ರೈಯರ್‌ಗಳನ್ನು ನೀಡಲು CSR ಫಂಡ್‌ಗಳೊಂದಿಗೆ ಕೆಲಸ ಮಾಡುತ್ತಿದ್ದೇವೆ.",
    csrBtn: "CSR ವಿವರ ಕೇಳಿ",

    // Farmer Stories Page
    storiesBadge: "ರೈತರ ಯಶಸ್ಸಿನ ಕಥೆಗಳು",
    storiesTitle1: "ನೈಜ ಕಥೆಗಳು. ನೈಜ ಅಭಿವೃದ್ಧಿ.",
    storiesTitle2: "ಬೆಳೆ ನಾಶವಿಲ್ಲದ ಕೃಷಿ.",
    storiesSubtitle: "ZeniTEK ಬಳಸಿ ಲಾಭ ಹೆಚ್ಚಿಸಿಕೊಂಡ ರೈತರ ಅನುಭವಗಳು.",
    impactFamilies: "ಫಲಾನುಭವಿ ಗ್ರಾಮೀಣ ಕುಟುಂಬಗಳು",
    impactValue: "ರೈತರಿಗೆ ಸಿಕ್ಕ ಹೆಚ್ಚುವರಿ ಲಾಭ",
    impactCrops: "ಉಳಿಸಿದ ಬೆಳೆಗಳು",
    impactCleanEnergy: "100% ಸೌರಶಕ್ತಿ",
    videoReviewsTitle: "ಗ್ರಾಹಕರ ವೀಡಿಯೊ ಅನಿಸಿಕೆಗಳು",
    videoReviewsSub: "ತಮಿಳುನಾಡು, ಕೇರಳ, ಮಹಾರಾಷ್ಟ್ರ ರೈತರ ವೀಡಿಯೊ ಸಂದರ್ಶನಗಳು.",
    caseStudiesTitle: "ಕೇಸ್ ಸ್ಟಡಿಗಳು",
    pollachiCollective: "ಪೊಳ್ಳಾಚಿ ತೆಂಗು ಬೆಳೆಗಾರರ ಸಂಘ",
    pollachiTitle: "50 ರೈತರು ಮಳೆಯ ನಷ್ಟ ತಡೆದು ಆದಾಯವನ್ನು 28% ಹೆಚ್ಚಿಸಿದ್ದು ಹೇಗೆ?",
    probTitle: "ಸಮಸ್ಯೆ",
    probDesc: "ಅಕಾಲಿಕ ಮಳೆಯಿಂದ 30% ಕೊಬ್ಬರಿ ಬೂಸ್ಟು ಹಿಡಿದು ಹಾಳಾಗುತ್ತಿತ್ತು.",
    solTitle: "ಪರಿಹಾರ",
    solDesc: "50% ಸಬ್ಸಿಡಿಯೊಂದಿಗೆ 500 ಕೆಜಿ ಸೋಲಾರ್ ಡ್ರೈಯರ್ ಅಳವಡಿಸಲಾಯಿತು.",
    resTitle: "ಫಲಿತಾಂಶ",
    resDesc: "2.5 ದಿನಗಳಲ್ಲಿ 100% ಉತ್ತಮ ದರ್ಜೆಯ ಬಿಳಿ ಕೊಬ್ಬರಿ. ಕೆಜಿಗೆ ₹18 ಹೆಚ್ಚುವರಿ ಲಾಭ.",
    commitmentTitle: "ನಮ್ಮ 360° ಬೆಂಬಲ ಭರವಸೆ",
    comm1Title: "ಸಂಪೂರ್ಣ ಸಬ್ಸಿಡಿ ನೆರವು",
    comm1Desc: "ಬ್ಯಾಂಕ್ ಸಾಲ ಮತ್ತು ಸಬ್ಸಿಡಿ ಅರ್ಜಿಗಳನ್ನು ನಾವೇ ನಿರ್ವಹಿಸುತ್ತೇವೆ.",
    comm2Title: "ಅನುಸ್ಥಾಪನೆ ಮತ್ತು ತರಬೇತಿ",
    comm2Desc: "ನಮ್ಮ ಇಂಜಿನಿಯರ್‌ಗಳು ಜಮೀನಿನಲ್ಲಿ ಅಳವಡಿಸಿ ತರಬೇತಿ ನೀಡುತ್ತಾರೆ.",
    comm3Title: "ಮಾರುಕಟ್ಟೆ ಸಂಪರ್ಕ",
    comm3Desc: "ಉತ್ಪನ್ನಗಳಿಗೆ ನೇರ ಮಾರುಕಟ್ಟೆ ಸಂಪರ್ಕ ಕಲ್ಪಿಸುತ್ತೇವೆ.",
    startProsperityBtn: "ಇಂದೇ ನಿಮ್ಮ ಯಶಸ್ಸಿನ ಪಯಣ ಆರಂಭಿಸಿ",

    // Gallery Page
    galleryBadge: "ಗ್ಯಾಲರಿ ಮತ್ತು ಯೋಜನೆಗಳು",
    galleryTitle1: "ZeniTEK ಸೋಲಾರ್ ಡ್ರೈಯರ್‌ಗಳು",
    galleryTitle2: "ಮತ್ತು ಉತ್ಪನ್ನಗಳ ಚಿತ್ರಗಳು",
    gallerySubtitle: "ವಿವಿಧ ರಾಜ್ಯಗಳಲ್ಲಿ ಅಳವಡಿಸಲಾದ ಡ್ರೈಯರ್‌ಗಳು ಮತ್ತು ಒಣಗಿಸಿದ ಉತ್ಪನ್ನಗಳ ಫೋಟೋಗಳು.",
    catAll: "ಎಲ್ಲಾ ಫೋಟೋಗಳು",
    catInstallations: "ಅಳವಡಿಸಿದ ಸ್ಥಳಗಳು",
    catProduce: "ಒಣಗಿಸಿದ ಉತ್ಪನ್ನ ಗುಣಮಟ್ಟ",
    catModels: "ಡ್ರೈಯರ್ ಮಾದರಿಗಳು",
    catFactory: "ಕಾರ್ಖಾನೆ",
    viewEnlarged: "ದೊಡ್ಡದಾಗಿ ನೋಡಿ",
    clickFullSpec: "ಸಂಪೂರ್ಣ ವಿವರಕ್ಕೆ ಕ್ಲಿಕ್ ಮಾಡಿ",
    customDryerBadge: "ನಿಮ್ಮ ಸೋಲಾರ್ ಡ್ರೈಯರ್ ಪಡೆಯಿರಿ",
    customDryerTitle: "ನಿಮಗೂ ಇಂತಹ ಸೋಲಾರ್ ಡ್ರೈಯರ್ ಬೇಕೇ?",
    customDryerDesc: "40%-60% ಸಬ್ಸಿಡಿ ನೆರವಿನೊಂದಿಗೆ ಡ್ರೈಯರ್‌ಗಳನ್ನು ನಿರ್ಮಿಸಿಕೊಡುತ್ತೇವೆ.",
    locationLabel: "ಸ್ಥಳ:",
    requestQuoteForModel: "ಈ ಮಾದರಿಯ ಬೆಲೆ ಕೇಳಿ",

    // Solar Dryers Page
    catalogueBadge: "ಸೋಲಾರ್ ಡ್ರೈಯರ್ ಕ್ಯಾಟಲಾಗ್",
    catalogueTitle1: "100% ಸೌರಶಕ್ತಿ ಡ್ರೈಯರ್‌ಗಳು.",
    catalogueTitle2: "5 ಪಟ್ಟು ವೇಗ. ಶೂನ್ಯ ಕರೆಂಟ್ ಬಿಲ್.",
    catalogueSubtitle: "ವಿವಿಧ ಮಾದರಿಯ ಡ್ರೈಯರ್‌ಗಳನ್ನು ನೋಡಿ. ಹೆಚ್ಚಿನ ವಿವರಗಳಿಗೆ ಕ್ಲಿಕ್ ಮಾಡಿ.",
    browseCapacity: "ಸಾಮರ್ಥ್ಯದ ಆಧಾರದಲ್ಲಿ",
    browseCrop: "ಬೆಳೆಯ ಆಧಾರದಲ್ಲಿ",
    clickSpecs: "ವಿವರಗಳಿಗೆ ಕ್ಲಿಕ್ ಮಾಡಿ",
    targetAudienceLabel: "ಯಾರಿಗೆ ಸೂಕ್ತ",
    buildMaterialLabel: "ತಯಾರಿಕಾ ವಸ್ತು",
    tempRangeLabel: "ತಾಪಮಾನ",
    subsidyEligibilityLabel: "ಸಬ್ಸಿಡಿ ಅರ್ಹತೆ",
    viewSpecsPhotos: "ವಿವರಗಳು & ಫೋಟೋ ನೋಡಿ",
    checkSubsidyPricing: "ಬೆಲೆ & ಸಬ್ಸಿಡಿ ತಿಳಿಯಿರಿ",
    thSpecParam: "ತಾಂತ್ರಿಕ ವಿವರಣೆ",
    thPortable: "ಸಣ್ಣ ಡ್ರೈಯರ್",
    thPolyhouse: "ಪಾಲಿಹೌಸ್ ಡ್ರೈಯರ್",
    thIndustrial: "ಇಂಡಸ್ಟ್ರಿಯಲ್ ಡ್ರೈಯರ್",
    stateAssistance: "ರಾಜ್ಯ ಸರ್ಕಾರಿ ಸಬ್ಸಿಡಿ ನೆರವು",
    claimSubsidyTitle: "60% ವರೆಗೆ ಸರ್ಕಾರಿ ಸಬ್ಸಿಡಿ ಪಡೆಯಿರಿ",
    claimSubsidyDesc: "NABARD ಮತ್ತು ಸರ್ಕಾರಿ ಸಬ್ಸಿಡಿ ಪ್ರಕ್ರಿಯೆಯಲ್ಲಿ ಸಂಪೂರ್ಣ ನೆರವು.",
    checkSubsidyBtn: "ಸಬ್ಸಿಡಿ ಅರ್ಹತೆ ನೋಡಿ",

    // Map Page & Component
    mapShowcaseBadge: "ನಕ್ಷೆ ಮಾಹಿತಿ",
    mapTitle1: "ಸಕ್ರಿಯ ಸೋಲಾರ್ ಡ್ರೈಯರ್‌ಗಳು",
    mapTitle2: "ದಕ್ಷಿಣ ಭಾರತದಾದ್ಯಂತ",
    mapSubtitle: "ನಕ್ಷೆಯಲ್ಲಿ ನಮ್ಮ ಡ್ರೈಯರ್‌ಗಳು ಅಳವಡಿಸಲಾದ ಸ್ಥಳಗಳು ಮತ್ತು ವಿವರಗಳನ್ನು ನೋಡಿ.",
    filterStateLabel: "ರಾಜ್ಯ ಆಯ್ಕೆಮಾಡಿ:",
    interactiveMapTab: "ನಕ್ಷೆ",
    projectListTab: "ಪಟ್ಟಿ",
    visitTitle: "ಹತ್ತಿರದ ಡ್ರైಯರ್ ನೇರವಾಗಿ ನೋಡಬೇಕೇ?",
    visitDesc: "ರೈತರಿಗಾಗಿ ನಾವು ನೇರ ಭೇಟಿ ವ್ಯವಸ್ಥೆ ಮಾಡುತ್ತೇವೆ.",
    bookVisitBtn: "ನೇರ ಭೇಟಿ ಬುಕ್ ಮಾಡಿ",

    // Footer
    footerAbout: "ಉನ್ನತ ಸಾಮರ್ಥ್ಯದ ಸೋಲಾರ್ ಡ್ರೈಯರ್‌ಗಳನ್ನು ತಯಾರಿಸುವ ಭಾರತದ ಪ್ರಮುಖ ಸಂಸ್ಥೆ.",
    footerDryerModels: "ಸೋಲಾರ್ ಡ್ರೈಯರ್ ಮಾದರಿಗಳು",
    footerDownloads: "ಡೌನ್‌ಲೋಡ್‌ಗಳು",
    footerCatalog: "ಉತ್ಪನ್ನ ಕ್ಯಾಟಲಾಗ್ (PDF)",
    footerSubsidyGuide: "ಸಬ್ಸಿಡಿ ಮಾರ್ಗದರ್ಶಿ 2026",
    footerLabReport: "ಕೊಬ್ಬರಿ ಪರೀಕ್ಷಾ ವರದಿ",
    footerCoimbatoreFactory: "ಕಚೇರಿಗಳು & ಸಂಪರ್ಕ",
    footerOffices: "ಕಚೇರಿಗಳು & ಸಂಪರ್ಕ",
    footerRights: "ಎಲ್ಲಾ ಹಕ್ಕುಗಳನ್ನು ಕಾಯ್ದಿರಿಸಲಾಗಿದೆ.",
    footerPrivacy: "ಗೌಪ್ಯತಾ ನೀತಿ",
    footerTerms: "ನಿಯಮಗಳು",

    // Crops
    cropCopra: "ಕೊಬ್ಬರಿ / ತೆಂಗು",
    cropMoringa: "ನುಗ್ಗೆ / ಸೊಪ್ಪು / ಟೀ",
    cropSpices: "ಮೆಣಸಿನಕಾಯಿ / ಸಾಂಬಾರು",
    cropFruits: "ಹಣ್ಣುಗಳು & ತರಕಾರಿಗಳು",
    cropFish: "ಒಣಮೀನು / ಸಿಗಡಿ",
    cropOther: "ಇತರ ಬೆಳೆಗಳು",

    // Models
    modelPortable: "ಸಣ್ಣ ಸೋಲಾರ್ ಡ್ರೈಯರ್",
    modelPolyhouse: "ಪಾಲಿಹೌಸ್ ಸೋಲಾರ್ ಡ್ರೈಯರ್",
    modelIndustrial: "ಇಂಡಸ್ಟ್ರಿಯಲ್ ಸೋಲಾರ್ ಡ್ರೈಯರ್"
  }
};

export const LanguageProvider = ({ children }) => {
  const [lang, setLang] = useState('en');

  const t = (key) => {
    return translations[lang]?.[key] || translations['en']?.[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);
