import React, { createContext, useContext, useState } from 'react';

const LanguageContext = createContext();

export const translations = {
  en: {
    announcement: "MNRE Approved & ISO 9001:2015 Certified | Factory: Coimbatore, Tamil Nadu",
    subsidyBadge: "40% - 60% Govt Subsidy Eligible",
    navHome: "Home",
    navAbout: "About Us",
    navDryers: "Solar Dryers",
    navApplications: "Applications",
    navGallery: "Gallery",
    navStories: "Farmer Stories",
    navMap: "Interactive Map",
    navContact: "Contact Us",
    getQuote: "Get Free Quote",
    heroBadge: "Next-Gen Solar Thermal Food Preservation Technology",
    heroTitle1: "Stop Post-Harvest Loss.",
    heroTitle2: "Multiply Your Farm Profits.",
    heroSubtitle: "Hygienic, 100% solar-powered thermal dehydration that retains color, aroma, and natural nutrients without electricity bills.",
    calcSavings: "Calculate My Savings",
    exploreModels: "Explore Dryer Models",
    dryersInstalled: "Dryers Installed",
    foodSaved: "Food Saved / Year",
    subsidyHelp: "Govt Subsidy Assistance",
    mnreBadge: "MNRE Approved & Enlisted",
    isoBadge: "ISO 9001:2015 Certified Quality",
    subsidyBadge2: "100% Eligible for State Subsidies",
    roiTitle: "Interactive Profit & Sizing Calculator",
    roiSubtitle: "Select your crop and daily harvest quantity to estimate drying speedup & profits.",
    selectCrop: "1. Select Your Crop / Material",
    batchQty: "2. Batch Harvest Quantity (kg)",
    sunDrying: "Open Sun Drying",
    solarDrying: "ZeniTEK Solar Dryer",
    daysFaster: "Days Faster (100% Sealed)",
    priceIncrease: "Market Price Premium",
    profitPerBatch: "Est. Profit & Savings / Batch",
    recSetup: "Recommended Setup",
    getQuoteSetup: "Get Quote for This Setup",
    modelsHeading: "Choose the Perfect Solar Thermal Dryer for Your Farm",
    modelsSubtitle: "From portable 10 kg batch units to heavy multi-tunnel plants for exporters.",
    reqQuote: "Request Price Quote",
    whatCanYouDry: "What Can You Dry With ZeniTEK?",
    viewAllCrops: "View All 50+ Crops Matrix",
    whyChooseUs: "Why Choose ZeniTEK Solar?",
    climateResilient: "Climate Resilient",
    climateDesc: "Works seamlessly on cloudy days with smart heat retention.",
    zeroOpCost: "Zero Operating Cost",
    zeroOpDesc: "100% sun-powered. Zero wood, zero coal, zero power bills.",
    hygienicSetup: "100% Hygienic Setup",
    hygienicDesc: "Fully sealed enclosure prevents dust, insects, and rain spoilage.",
    marketLinkage: "Market Linkage Support",
    marketDesc: "Direct B2B corporate buyer connection for dried produce.",
    trustedBy: "Trusted by 1,200+ Agricultural Entrepreneurs",
    quickFormTitle: "Get Instant Subsidy & Pricing Details on WhatsApp",
    quickFormDesc: "Fill this 30-second form to receive custom dryer sizing and subsidy guidelines.",
    yourName: "Your Name",
    whatsappNum: "WhatsApp Number",
    districtCity: "District / City",
    targetCrop: "Target Crop",
    getSubsidyQuote: "Get Subsidy Quote",
    factoryLocation: "Coimbatore Headquarters & Works",
    callUs: "Call Engineering Support",
    emailUs: "Email Sales Team",
    chatWhatsapp: "Chat Instantly on WhatsApp",
    userCategory: "User Category",
    desiredCapacity: "Desired Daily Capacity",
    additionalReqs: "Additional Requirements",
    submitProposal: "Submit & Request Formal Proposal",
    seeMoreDetails: "See More Details",
    enquireSetup: "Enquire Setup",
    projectDetails: "Installation Case Details",
    moistureReduction: "Moisture Parameter Target",
    close: "Close"
  },
  ta: {
    announcement: "MNRE அங்கீகாரம் & ISO 9001:2015 சான்றளிக்கப்பட்டது | தொழிற்சாலை: கோயம்பத்தூர்",
    subsidyBadge: "40% - 60% அரசு மானியம் பெறத் தகுதியானது",
    navHome: "முகப்பு",
    navAbout: "எங்களைப் பற்றி",
    navDryers: "சோலார் உலர்த்திகள்",
    navApplications: "பயன்பாடுகள்",
    navGallery: "படத்தொகுப்பு",
    navStories: "விவசாயி கதைகள்",
    navMap: "ஊடாடும் வரைபடம்",
    navContact: "தொடர்பு கொள்ள",
    getQuote: "இலவச விலைப்புள்ளி பெற",
    heroBadge: "அடுத்த தலைமுறை சோலார் உணவு பதப்படுத்தும் தொழில்நுட்பம்",
    heroTitle1: "அறுவடைக்குப் பிந்தைய இழப்பைத் தடுப்போம்.",
    heroTitle2: "விவசாய லாபத்தை பன்மடங்கு பெருக்குவோம்.",
    heroSubtitle: "மின்சாரக் கட்டணம் இன்றி நிறம், மணம் மற்றும் இயற்கை ஊட்டச்சத்துக்களைக் காக்கும் 100% சூரிய ஒளி உலர்த்தி.",
    calcSavings: "எனது சேமிப்பைக் கணக்கிடுக",
    exploreModels: "உலர்த்தி மாடல்களைக் காண்க",
    dryersInstalled: "நிறுவப்பட்ட உலர்த்திகள்",
    foodSaved: "ஆண்டுக்கு சேமிக்கப்பட்ட உணவு",
    subsidyHelp: "அரசு மானிய உதவி",
    mnreBadge: "MNRE அங்கீகரிக்கப்பட்ட தயாரிப்பு",
    isoBadge: "ISO 9001:2015 தரச் சான்றிதழ்",
    subsidyBadge2: "100% மாநில மானியத் தகுதி",
    roiTitle: "லாப மற்றும் அளவு கணக்கீடு",
    roiSubtitle: "உங்கள் பயிர் மற்றும் தினசரி விளைச்சலைத் தேர்ந்தெடுத்து உலர்த்தும் வேகத்தையும் லாபத்தையும் கணக்கிடுங்கள்.",
    selectCrop: "1. பயிர் / பொருளைத் தேர்ந்தெடுக்கவும்",
    batchQty: "2. தொகுதி விளைச்சல் அளவு (கி.கி)",
    sunDrying: "திறந்தவெளி சூரிய உலர்த்தல்",
    solarDrying: "ஜெனிலெக் சோலார் உலர்த்தி",
    daysFaster: "நாட்கள் அதிவேக உலர்த்தல் (பாதுகாப்பானது)",
    priceIncrease: "சந்தை விலை உயர்வு %",
    profitPerBatch: "ஒரு தொகுதிக்கு எதிர்பார்க்கப்படும் லாபம்",
    recSetup: "பரிந்துரைக்கப்படும் உலர்த்தி",
    getQuoteSetup: "இதற்கான விலைப்புள்ளி பெற",
    modelsHeading: "உங்கள் பண்ணைக்கு ஏற்ற சோலார் உலர்த்தியைத் தேர்ந்தெடுக்கவும்",
    modelsSubtitle: "10 கி.கி சிறிய உலர்த்தி முதல் 1 டன் தொழில்முறை உலர்த்தி வரை.",
    reqQuote: "விலைப்புள்ளி கேட்க",
    whatCanYouDry: "ஜெனிலெக் மூலம் எவற்றையெல்லாம் உலர்த்தலாம்?",
    viewAllCrops: "அனைத்து 50+ பயிர் அட்டவணையைக் காண்க",
    whyChooseUs: "ஏன் ஜெனிலெக் சோலார்?",
    climateResilient: "காலநிலை தாங்கும் திறன்",
    climateDesc: "மேகமூட்டமான நாட்களிலும் வெப்பத்தைத் தக்கவைத்துச் செயல்படும்.",
    zeroOpCost: "பூஜ்ஜிய இயக்கச் செலவு",
    zeroOpDesc: "100% சூரிய ஒளி சக்தி. விறகு இல்லை, கரண்ட் பில் இல்லை.",
    hygienicSetup: "100% சுகாதாரமான உலர்த்தல்",
    hygienicDesc: "தூசி, பூச்சிகள் மற்றும் மழைப் பாதிப்பிலிருந்து முழுப் பாதுகாப்பு.",
    marketLinkage: "சந்தை இணைப்பு உதவி",
    marketDesc: "உலர்ந்த பொருட்களுக்கு நேரடி கார்ப்பரேட் வாங்குபவர் இணைப்பு.",
    trustedBy: "1,200+ விவசாயிகளால் நம்பப்படுகிறது",
    quickFormTitle: "வாட்ஸ்அப்பில் உடனடி மானியம் & விலை விவரம் பெற",
    quickFormDesc: "மானிய வழிகாட்டுதல்களைப் பெற 30 வினாடி படிவத்தைப் பூர்த்தி செய்யவும்.",
    yourName: "உங்கள் பெயர்",
    whatsappNum: "வாட்ஸ்அப் எண்",
    districtCity: "மாவட்டம் / ஊர்",
    targetCrop: "உலர்த்தும் பயிர்",
    getSubsidyQuote: "மானிய விலைப்புள்ளி பெற",
    factoryLocation: "கோயம்பத்தூர் தலைமையகம் & தொழிற்சாலை",
    callUs: "பொறியியல் உதவிக்கு அழைக்கவும்",
    emailUs: "விற்பனை பிரிவுக்கு மின்னஞ்சல் செய்ய",
    chatWhatsapp: "வாட்ஸ்அப்பில் உடனடியாக அரட்டையடிக்க",
    userCategory: "பயனர் பிரிவு",
    desiredCapacity: "தேவையான உலர்த்தி திறன்",
    additionalReqs: "கூடுதல் விவரங்கள்",
    submitProposal: "சமர்ப்பித்து அதிகாரப்பூர்வ மதிப்பீடு பெற",
    seeMoreDetails: "கூடுதல் விவரங்கள் காண்க",
    enquireSetup: "விலைப்புள்ளி கேட்க",
    projectDetails: "திட்டத்தின் முழு விவரங்கள்",
    moistureReduction: "ஈரப்பத அளவு இலக்கு",
    close: "மூடுக"
  },
  hi: {
    announcement: "MNRE स्वीकृत एवं ISO 9001:2015 प्रमाणित | कारखाना: कोयंबटूर, तमिलनाडु",
    subsidyBadge: "40% - 60% सरकारी सब्सिडी योग्य",
    navHome: "होम",
    navAbout: "हमारे बारे में",
    navDryers: "सोलर ड्रायर",
    navApplications: "अनुप्रयोग",
    navGallery: "गैलरी",
    navStories: "किसान गाथाएं",
    navMap: "मानचित्र",
    navContact: "संपर्क करें",
    getQuote: "निःशुल्क कोटेशन पाएं",
    heroBadge: "अगली पीढ़ी की सोलर थर्मल खाद्य संरक्षण तकनीक",
    heroTitle1: "फसल के नुकसान को रोकें।",
    heroTitle2: "कृषि मुनाफा कई गुना बढ़ाएं।",
    heroSubtitle: "बिना बिजली बिल के प्राकृतिक रंग, सुगंध और पोषक तत्वों को सुरक्षित रखने वाला 100% सौर ऊर्जा संचालित ड्रायर।",
    calcSavings: "अपनी बचत की गणना करें",
    exploreModels: "सोलर ड्रायर मॉडल देखें",
    dryersInstalled: "स्थापित सोलर ड्रायर",
    foodSaved: "वार्षिक बचाई गई उपज",
    subsidyHelp: "सरकारी सब्सिडी सहायता",
    mnreBadge: "MNRE स्वीकृत उत्पाद",
    isoBadge: "ISO 9001:2015 गुणवत्ता प्रमाणित",
    subsidyBadge2: "100% राज्य सब्सिडी पात्रता",
    roiTitle: "लाभ एवं आकार कैलकुलेटर",
    roiSubtitle: "अपनी फसल और दैनिक मात्रा का चयन करके सुखाने की गति और बचत का अनुमान लगाएं।",
    selectCrop: "1. अपनी फसल / सामग्री चुनें",
    batchQty: "2. बैच उपज मात्रा (किग्रा)",
    sunDrying: "खुली धूप में सुखाना",
    solarDrying: "ZeniTEK सोलर ड्रायर",
    daysFaster: "दिन तेजी से सुखाना (सुरक्षित)",
    priceIncrease: "बाजार मूल्य वृद्धि %",
    profitPerBatch: "प्रति बैच अनुमानित लाभ व बचत",
    recSetup: "अनुशंसित मॉडल",
    getQuoteSetup: "कोटेशन प्राप्त करें",
    modelsHeading: "अपने खेत के लिए सही सोलर ड्रायर चुनें",
    modelsSubtitle: "10 किग्रा घरेलू ड्रायर से लेकर 1 टन औद्योगिक प्लांट तक।",
    reqQuote: "मूल्य कोटेशन मांगें",
    whatCanYouDry: "ZeniTEK से आप क्या सुखा सकते हैं?",
    viewAllCrops: "सभी 50+ फसल सूची देखें",
    whyChooseUs: "ZeniTEK सोलर क्यों चुनें?",
    climateResilient: "मौसम प्रतिरोधी",
    climateDesc: "बादल वाले दिनों में भी निरंतर कार्य करता है।",
    zeroOpCost: "शून्य संचालन लागत",
    zeroOpDesc: "100% सौर ऊर्जा। कोई लकड़ी, कोयला या बिजली बिल नहीं।",
    hygienicSetup: "100% स्वच्छ प्रक्रिया",
    hygienicDesc: "धूल, कीड़ों और बारिश से पूर्ण सुरक्षा।",
    marketLinkage: "बाजार संबंध सहायता",
    marketDesc: "सूखे उत्पादों के लिए सीधे खरीदारों से जुड़ाव।",
    trustedBy: "1,200+ किसानों द्वारा विश्वसनीय",
    quickFormTitle: "व्हाट्सएप पर तुरंत सब्सिडी व मूल्य विवरण पाएं",
    quickFormDesc: "सब्सिडी की जानकारी के लिए 30 सेकंड का फॉर्म भरें।",
    yourName: "आपका नाम",
    whatsappNum: "व्हाट्सएप नंबर",
    districtCity: "जिला / शहर",
    targetCrop: "फसल का प्रकार",
    getSubsidyQuote: "सब्सिडी कोटेशन पाएं",
    factoryLocation: "कोयंबटूर मुख्यालय और कारखाना",
    callUs: "इंजीनियरिंग सहायता के लिए कॉल करें",
    emailUs: "बिक्री टीम को ईमेल करें",
    chatWhatsapp: "व्हाट्सएप पर तुरंत चैट करें",
    userCategory: "उपयोगकर्ता श्रेणी",
    desiredCapacity: "आवश्यक ड्रायर क्षमता",
    additionalReqs: "अतिरिक्त विवरण",
    submitProposal: "प्रस्ताव के लिए जमा करें",
    seeMoreDetails: "अधिक विवरण देखें",
    enquireSetup: "कोटेशन मांगें",
    projectDetails: "परियोजना विवरण",
    moistureReduction: "नमी का स्तर",
    close: "बंद करें"
  },
  ml: {
    announcement: "MNRE അംഗീകൃത & ISO 9001:2015 സർട്ടിഫൈഡ് | ഫാക്ടറി: കോയമ്പത്തൂർ",
    subsidyBadge: "40% - 60% സർക്കാർ സബ്സിഡി ലഭ്യം",
    navHome: "ഹോം",
    navAbout: "ഞങ്ങളെക്കുറിച്ച്",
    navDryers: "സോളാർ ഡ്രയറുകൾ",
    navApplications: "ഉപയോഗങ്ങൾ",
    navGallery: "ഗ്യാലറി",
    navStories: "കർഷക കഥകൾ",
    navMap: "മാപ്പ്",
    navContact: "ബന്ധപ്പെടുക",
    getQuote: "സൗജന്യ വിലവിവരം നേടൂ",
    heroBadge: "അത്യാധുനിക സോളാർ തെർമൽ ഉണക്കൽ സാങ്കേതികവിദ്യ",
    heroTitle1: "വിളനാശം തടയൂ.",
    heroTitle2: "കാർഷിക ലാഭം വർദ്ധിപ്പിക്കൂ.",
    heroSubtitle: "വൈദ്യുതി ബില്ലില്ലാതെ ഗുണമേന്മയും മണവും നിറവും നിലനിർത്തുന്ന 100% സോളാർ ഡ്രയറുകൾ.",
    calcSavings: "ലാഭം കണക്കാക്കൂ",
    exploreModels: "മോഡലുകൾ കാണുക",
    dryersInstalled: "സ്ഥാപിച്ച ഡ്രയറുകൾ",
    foodSaved: "സംരക്ഷിച്ച ഭക്ഷണം/വർഷം",
    subsidyHelp: "സർക്കാർ സബ്സിഡി സഹായം",
    mnreBadge: "MNRE അംഗീകൃത ഡ്രയർ",
    isoBadge: "ISO 9001:2015 സർട്ടിഫൈഡ്",
    subsidyBadge2: "100% സംസ്ഥാന സബ്സിഡി അർഹത",
    roiTitle: "ലാഭവും അളവും കണക്കാക്കാം",
    roiSubtitle: "നിങ്ങളുടെ വിളയും അളവും തിരഞ്ഞെടുത്ത് ഉണങ്ങുന്ന സമയവും ലാഭവും കണക്കാക്കൂ.",
    selectCrop: "1. വിള തിരഞ്ഞെടുക്കുക",
    batchQty: "2. അളവ് (കിലോ)",
    sunDrying: "തുറസ്സായ വെയിലിൽ ഉണക്കൽ",
    solarDrying: "ZeniTEK സോളാർ ഡ്രയർ",
    daysFaster: "ദിവസങ്ങൾ വേഗത്തിൽ ഉണങ്ങുന്നു",
    priceIncrease: "വിപണി വില വർദ്ധനവ് %",
    profitPerBatch: "പ്രതീക്ഷിക്കുന്ന ലാഭം",
    recSetup: "അനുയോജ്യമായ മോഡൽ",
    getQuoteSetup: "വിലവിവരം നേടുക",
    modelsHeading: "നിങ്ങളുടെ ആവശ്യത്തിനനുസരിച്ചുള്ള സോളാർ ഡ്രയറുകൾ",
    modelsSubtitle: "10 കിലോ ഗാർഹിക ഡ്രയർ മുതൽ 1 ടൺ വ്യവസായ ഡ്രയർ വരെ.",
    reqQuote: "വിലവിവരം ചോദിക്കൂ",
    whatCanYouDry: "സെനിടെക് ഉപയോഗിച്ച് എന്തൊക്കെ ഉണക്കാം?",
    viewAllCrops: "എല്ലാ 50+ വിളകളുടെ പട്ടിക കാണുക",
    whyChooseUs: "എന്തുകൊണ്ട് സെനിടെക് സോളാർ?",
    climateResilient: "കാലാവസ്ഥയെ ചെറുക്കുന്നു",
    climateDesc: "മേഘാവൃതമായ ദിവസങ്ങളിലും ചൂട് നിലനിർത്തുന്നു.",
    zeroOpCost: "സീറോ പ്രവർത്തന ചിലവ്",
    zeroOpDesc: "100% സൂര്യപ്രകാശം. വിറകോ കറന്റ് ബില്ലോ ഇല്ല.",
    hygienicSetup: "100% ശുചിത്വമുള്ള ഉണക്കൽ",
    hygienicDesc: "പൊടി, പ്രാണികൾ, മഴ എന്നിവയിൽ നിന്ന് പൂർണ്ണ സംരക്ഷണം.",
    marketLinkage: "വിപണി സഹായം",
    marketDesc: "ഉണക്കിയ ഉൽപ്പന്നങ്ങൾക്ക് നേരിട്ടുള്ള വിപണി ബന്ധം.",
    trustedBy: "1,200+ കർഷകർ വിശ്വസിക്കുന്നു",
    quickFormTitle: "വാട്സാപ്പിൽ സബ്സിഡിയും വിലവിവരങ്ങളും അറിയൂ",
    quickFormDesc: "വിവരങ്ങൾക്ക് 30 സെക്കൻഡ് ഫോം പൂരിപ്പിക്കൂ.",
    yourName: "നിങ്ങളുടെ പേര്",
    whatsappNum: "വാട്സാപ്പ് നമ്പർ",
    districtCity: "ജില്ല / സ്ഥലം",
    targetCrop: "ഉണക്കേണ്ട വിള",
    getSubsidyQuote: "സബ്സിഡി വിലവിവരം നേടൂ",
    factoryLocation: "കോയമ്പത്തൂർ ഹെഡ് ഓഫീസ് & ഫാക്ടറി",
    callUs: "എഞ്ചിനീയറിംഗ് സഹായത്തിന് വിളിക്കൂ",
    emailUs: "സെയിൽസ് ടീമിന് ഇമെയിൽ അയക്കൂ",
    chatWhatsapp: "വാട്സാപ്പിൽ മെസ്സേജ് അയക്കൂ",
    userCategory: "വിഭാഗം",
    desiredCapacity: "ആവശ്യമായ ശേഷി",
    additionalReqs: "കൂടുതൽ വിവരങ്ങൾ",
    submitProposal: "വിവരങ്ങൾ അയക്കൂ",
    seeMoreDetails: "കൂടുതൽ വിവരങ്ങൾ കാണുക",
    enquireSetup: "അന്വേഷിക്കുക",
    projectDetails: "പദ്ധതി വിവരങ്ങൾ",
    moistureReduction: "ഈർപ്പത്തിന്റെ അളവ്",
    close: "അടയ്ക്കുക"
  },
  te: {
    announcement: "MNRE గుర్తింపు పొందినది & ISO 9001:2015 సర్టిఫైడ్ | ఫ్యాక్టరీ: కోయంబత్తూర్",
    subsidyBadge: "40% - 60% ప్రభుత్వ సబ్సిడీ అర్హత",
    navHome: "హోమ్",
    navAbout: "మా గురించి",
    navDryers: "సోలార్ డ్రైయర్లు",
    navApplications: "ఉపయోగాలు",
    navGallery: "గ్యాలరీ",
    navStories: "రైతు కథలు",
    navMap: "మ్యాప్",
    navContact: "సంప్రదించండి",
    getQuote: "ఉచిత కొటేషన్ పొందండి",
    heroBadge: "నెక్స్ట్-జెన్ సోలార్ థర్మల్ ఆహార పరిరక్షణ సాంకేతికత",
    heroTitle1: "పంట నష్టాన్ని నివారించండి.",
    heroTitle2: "వ్యవసాయ లాభాలను రెట్టింపు చేయండి.",
    heroSubtitle: "కరెంట్ బిల్లు లేకుండా రంగు, రుచి, పోషకాలను కాపాడే 100% సౌరశక్తి డ్రైయర్.",
    calcSavings: "లాభాన్ని లెక్కించండి",
    exploreModels: "డ్రైయర్ మోడల్స్ చూడండి",
    dryersInstalled: "ఏర్పాటు చేసిన డ్రైయర్లు",
    foodSaved: "సంవత్సరానికి కాపాడిన పంట",
    subsidyHelp: "ప్రభుత్వ సబ్సిడీ సహాయం",
    mnreBadge: "MNRE ఆమోదించిన మోడల్",
    isoBadge: "ISO 9001:2015 సర్టిఫైడ్ క్వాలిటీ",
    subsidyBadge2: "100% రాష్ట్ర సబ్సిడీ అర్హత",
    roiTitle: "లాభం మరియు పరిమాణ లెక్కింపు",
    roiSubtitle: "మీ పంట మరియు రోజువారీ పరిమాణాన్ని ఎంచుకుని ఆదా అయ్యే సమయం మరియు లాభాన్ని తెలుసుకోండి.",
    selectCrop: "1. పంటను ఎంచుకోండి",
    batchQty: "2. రోజువారీ దిగుబడి (కిలోలు)",
    sunDrying: "బహిరంగ ఎండలో ఆరబెట్టడం",
    solarDrying: "ZeniTEK సోలార్ డ్రైయర్",
    daysFaster: "రోజులు వేగంగా ఆరుతుంది",
    priceIncrease: "మార్కెట్ ధర పెరుగుదల %",
    profitPerBatch: "అంచనా లాభం & పొదుపు",
    recSetup: "సూచించిన మోడల్",
    getQuoteSetup: "కొటేషన్ పొందండి",
    modelsHeading: "మీ పొలానికి తగిన సోలార్ డ్రైయర్‌ను ఎంచుకోండి",
    modelsSubtitle: "10 కిలోల చిన్న డ్రైయర్ నుండి 1 టన్ను పారిశ్రామిక డ్రైయర్ వరకు.",
    reqQuote: "ధర కొటేషన్ అడగండి",
    whatCanYouDry: "ZeniTEK తో ఏమేమి ఆరబెట్టవచ్చు?",
    viewAllCrops: "అన్ని 50+ పంటల జాబితా చూడండి",
    whyChooseUs: "ZeniTEK సోలార్ ఎందుకు ఎంచుకోవాలి?",
    climateResilient: "వాతావరణ నిరోధకత",
    climateDesc: "మబ్బుల రోజుల్లో కూడా వేడిని నిలిపి ఉంచుతుంది.",
    zeroOpCost: "సున్నా నిర్వహణ ఖర్చు",
    zeroOpDesc: "100% సౌరశక్తి. కట్టెలు, కరెంట్ బిల్లుల అవసరం లేదు.",
    hygienicSetup: "100% పరిశుభ్రమైన ఆరబెట్టడం",
    hygienicDesc: "ధూళి, పురుగులు, వర్షం నుండి పూర్తి రక్షణ.",
    marketLinkage: "మార్కెటింగ్ సహాయం",
    marketDesc: "ఎండిన ఉత్పత్తులకు నేరుగా కొనుగోలుదారుల అనుసంధానం.",
    trustedBy: "1,200+ మంది రైతుల నమ్మకం",
    quickFormTitle: "వాట్సాప్‌లో తక్షణ సబ్సిడీ & ధరల వివరాలు పొందండి",
    quickFormDesc: "వివరాల కోసం 30 సెకన్ల ఫారమ్‌ను నింపండి.",
    yourName: "మీ పేరు",
    whatsappNum: "వాట్సాప్ నంబర్",
    districtCity: "జిల్లా / ఊరు",
    targetCrop: "ఆరబెట్టే పంట",
    getSubsidyQuote: "సబ్సిడీ వివరాలు పొందండి",
    factoryLocation: "కోయంబత్తూర్ ప్రధాన కార్యాలయం & ఫ్యాక్టరీ",
    callUs: "ఇంజనీరింగ్ సహాయం కోసం కాల్ చేయండి",
    emailUs: "సేల్స్ టీమ్‌కు ఇమెయిల్ చేయండి",
    chatWhatsapp: "వాట్సాప్‌లో చాట్ చేయండి",
    userCategory: "విభాగం",
    desiredCapacity: "కావలసిన సామర్థ్యం",
    additionalReqs: "అదనపు వివరాలు",
    submitProposal: "వివరాలు సమర్పించండి",
    seeMoreDetails: "మరిన్ని వివరాలు చూడండి",
    enquireSetup: "వివరాలు అడగండి",
    projectDetails: "ప్రాజెక్ట్ వివరాలు",
    moistureReduction: "తడి శాతం గురి",
    close: "మూసివేయి"
  },
  kn: {
    announcement: "MNRE അംഗീകൃത & ISO 9001:2015 ಪ್ರಮಾಣೀಕೃತ | ಕಾರ್ಖಾನೆ: ಕೊಯಮತ್ತೂರು",
    subsidyBadge: "40% - 60% ಸರ್ಕಾರಿ ಸಬ್ಸಿಡಿ ಲಭ್ಯ",
    navHome: "ಮುಖಪುಟ",
    navAbout: "ನಮ್ಮ ಬಗ್ಗೆ",
    navDryers: "ಸೋಲಾರ್ ಡ್ರೈಯರ್‌ಗಳು",
    navApplications: "ಅನ್ವಯಗಳು",
    navGallery: "ಗ್ಯಾಲರಿ",
    navStories: "ರೈತರ ಕಥೆಗಳು",
    navMap: "ನಕ್ಷೆ",
    navContact: "ಸಂಪರ್ಕಿಸಿ",
    getQuote: "ಉಚಿತ ಧಾರಣೆ ಪಡೆಯಿರಿ",
    heroBadge: "ಮುಂದಿನ ಪೀಳಿಗೆಯ ಸೋಲಾರ್ ಥರ್ಮಲ್ ಆಹಾರ ಸಂರಕ್ಷಣಾ ತಂತ್ರಜ್ಞಾನ",
    heroTitle1: "ಕೊಯ್ಲೋತ್ತರ ನಷ್ಟ ತಡೆಯಿರಿ.",
    heroTitle2: "ಕೃಷಿ ಲಾಭವನ್ನು ಹೆಚ್ಚಿಸಿ.",
    heroSubtitle: "ವಿದ್ಯುತ್ ಬಿಲ್ ಇಲ್ಲದೆ ಬಣ್ಣ, ಸುವಾಸನೆ ಮತ್ತು ಪೋಷಕಾಂಶಗಳನ್ನು ಕಾಯ್ದುಕೊಳ್ಳುವ 100% ಸೌರಶಕ್ತಿ ಡ್ರೈಯರ್.",
    calcSavings: "ಬಳಕೆಯ ಉಳಿತಾಯ ಲೆಕ್ಕಹಾಕಿ",
    exploreModels: "ಡ್ರೈಯರ್ ಮಾದರಿಗಳನ್ನು ನೋಡಿ",
    dryersInstalled: "ಅಳವಡಿಸಲಾದ ಡ್ರೈಯರ್‌ಗಳು",
    foodSaved: "ವರ್ಷಕ್ಕೆ ಉಳಿಸಿದ ಬೆಳೆ",
    subsidyHelp: "ಸರ್ಕಾರಿ ಸಬ್ಸಿಡಿ ನೆರವು",
    mnreBadge: "MNRE ಅನುಮೋದಿತ ಮಾದರಿ",
    isoBadge: "ISO 9001:2015 ಗುಣಮಟ್ಟದ ಪ್ರಮಾಣಪತ್ರ",
    subsidyBadge2: "100% ರಾಜ್ಯ ಸಬ್ಸಿಡಿ ಅರ್ಹತೆ",
    roiTitle: "ಲಾಭ ಮತ್ತು ಸಾಮರ್ಥ್ಯ ಲೆಕ್ಕಾಚಾರ",
    roiSubtitle: "ನಿಮ್ಮ ಬೆಳೆ ಮತ್ತು ಪ್ರಮಾಣ ಆಯ್ಕೆಮಾಡಿ ಒಣಗಿಸುವ ಸಮಯ ಹಾಗೂ ಲಾಭ ತಿಳಿಯಿರಿ.",
    selectCrop: "1. ಬೆಳೆ ಆಯ್ಕೆಮಾಡಿ",
    batchQty: "2. ಬ್ಯಾಚ್ ಇಳುವರಿ ಪ್ರಮಾಣ (ಕೆಜಿ)",
    sunDrying: "ಬಯಲು ಬಿಸಿಲಿನಲ್ಲಿ ಒಣಗಿಸುವುದು",
    solarDrying: "ZeniTEK ಸೋಲಾರ್ ಡ್ರೈಯರ್",
    daysFaster: "ದಿನಗಳ ವೇಗದ ಒಣಗಿಸುವಿಕೆ",
    priceIncrease: "ಮಾರುಕಟ್ಟೆ ಬೆಲೆ ಏರಿಕೆ %",
    profitPerBatch: "ಅಂದಾಜು ಲಾಭ ಮತ್ತು ಉಳಿತಾಯ",
    recSetup: "ಶಿಫಾರಸು ಮಾಡಿದ ಮಾದರಿ",
    getQuoteSetup: "ಧಾರಣೆ ಪಡೆಯಿರಿ",
    modelsHeading: "ನಿಮ್ಮ ಜಮೀನಿಗೆ ಸೂಕ್ತವಾದ ಸೋಲಾರ್ ಡ್ರೈಯರ್ ಆಯ್ಕೆಮಾಡಿ",
    modelsSubtitle: "10 ಕೆಜಿ ಗೃಹಬಳಕೆಯ ಡ್ರೈಯರ್‌ನಿಂದ 1 ಟನ್ ಕೈಗಾರಿಕಾ ಡ್ರೈಯರ್‌ವರೆಗೆ.",
    reqQuote: "ಧಾರಣೆ ವಿನಂತಿಸಿ",
    whatCanYouDry: "ZeniTEK ಮೂಲಕ ಏನನ್ನೆಲ್ಲಾ ಒಣಗಿಸಬಹುದು?",
    viewAllCrops: "ಎಲ್ಲಾ 50+ ಬೆಳೆಗಳ ಪಟ್ಟಿ ನೋಡಿ",
    whyChooseUs: "ZeniTEK ಸೋಲಾರ್ ಏಕೆ ಆಯ್ಕೆ ಮಾಡಬೇಕು?",
    climateResilient: "ಹವಾಮಾನ ನಿರೋಧಕ",
    climateDesc: "ಮೋಡ ಕವಿದ ದಿನಗಳಲ್ಲೂ ಶಾಖವನ್ನು ಕಾಯ್ದುಕೊಳ್ಳುತ್ತದೆ.",
    zeroOpCost: "ಶೂನ್ಯ ನಿರ್ವಹಣಾ ವೆಚ್ಚ",
    zeroOpDesc: "100% ಸೌರಶಕ್ತಿ. ಸೌದೆ, ವಿದ್ಯುತ್ ಬಿಲ್ ಅಗತ್ಯವಿಲ್ಲ.",
    hygienicSetup: "100% ನೈರ್ಮಲ್ಯದ ಒಣಗಿಸುವಿಕೆ",
    hygienicDesc: "ಧೂಳು, ಕೀಟಗಳು ಮತ್ತು ಮಳೆಯಿಂದ ಸಂಪೂರ್ಣ ರಕ್ಷಣೆ.",
    marketLinkage: "ಮಾರುಕಟ್ಟೆ ನೆರವು",
    marketDesc: "ಒಣಗಿಸಿದ ಉತ್ಪನ್ನಗಳಿಗೆ ನೇರ ಮಾರುಕಟ್ಟೆ ಸಂಪರ್ಕ.",
    trustedBy: "1,200+ ರೈತರ ನಂಬಿಕೆ",
    quickFormTitle: "ವಾಟ್ಸಾಪ್‌ನಲ್ಲಿ ತಕ್ಷಣದ ಸಬ್ಸಿಡಿ ಮತ್ತು ಬೆಲೆ ವಿವರ ಪಡೆಯಿರಿ",
    quickFormDesc: "ಮಾಹಿತಿಗಾಗಿ 30 ಸೆಕೆಂಡ್‌ಗಳ ಅರ್ಜಿ ಭರ್ತಿ ಮಾಡಿ.",
    yourName: "ನಿಮ್ಮ ಹೆಸರು",
    whatsappNum: "ವಾಟ್ಸಾಪ್ ಸಂಖ್ಯೆ",
    districtCity: "ಜಿಲ್ಲೆ / ಊರು",
    targetCrop: "ಒಣಗಿಸುವ ಬೆಳೆ",
    getSubsidyQuote: "ಸಬ್ಸಿಡಿ ಧಾರಣೆ ಪಡೆಯಿರಿ",
    factoryLocation: "ಕೊಯಮತ್ತೂರು ಪ್ರಧಾನ ಕಚೇರಿ ಮತ್ತು ಕಾರ್ಖಾನೆ",
    callUs: "ಇಂಜಿನಿಯರಿಂಗ್ ನೆರವಿಗಾಗಿ ಕರೆ ಮಾಡಿ",
    emailUs: "ಸೇಲ್ಸ್ ತಂಡಕ್ಕೆ ಇಮೇಲ್ ಮಾಡಿ",
    chatWhatsapp: "ವಾಟ್ಸಾಪ್‌ನಲ್ಲಿ ತಕ್ಷಣ ಚಾಟ್ ಮಾಡಿ",
    userCategory: "ವರ್ಗ",
    desiredCapacity: "ಅಗತ್ಯವಿರುವ ಸಾಮರ್ಥ್ಯ",
    additionalReqs: "ಹೆಚ್ಚಿನ ವಿವರಗಳು",
    submitProposal: "ಅರ್ಜಿ ಸಲ್ಲಿಸಿ",
    seeMoreDetails: "ಹೆಚ್ಚಿನ ವಿವರಗಳನ್ನು ನೋಡಿ",
    enquireSetup: "ಧಾರಣೆ ಕೇಳಿ",
    projectDetails: "ಯೋಜನೆಯ ವಿವರಗಳು",
    moistureReduction: "ತೇವಾಂಶದ ಮಟ್ಟ",
    close: "ಮುಚ್ಚಿ"
  }
};

export const LanguageProvider = ({ children }) => {
  const [lang, setLang] = useState('en');

  const t = (key) => {
    return translations[lang]?.[key] || translations['en']?.[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);
